"""Normalize service names across tools to canonical identifiers."""

# Maps variant names to a single canonical name
ALIASES = {
    "acm-pca": "acmpca",
    "application-autoscaling": "applicationautoscaling",
    "cognito-identity": "cognitoidentity",
    "monitoring": "cloudwatch",
    "codestar-connections": "codeconnections",
    "elasticfilesystem": "efs",
    "elasticloadbalancing": "elb",
    "elasticmapreduce": "emr",
    "emr-serverless": "emrserverless",
    "iot-data": "iotdata",
    "email": "ses",
    "rds-data": "rdsdata",
    "redshift-data": "redshiftdata",
    "resourcegroupstaggingapi": "tagging",
    "sso-admin": "ssoadmin",
    "states": "stepfunctions",
    "timestream-query": "timestreamquery",
    "timestream-write": "timestreamwrite",
    "waf": "wafv2",
    "waf-regional": "wafv2",
    "airflow": "mwaa",
    "eks-auth": "eks",
}

# Internal/metadata services to exclude from comparison
INTERNAL = {"imds", "ecs-metadata", "s3files", "appsync-events", "cloudfront-keyvaluestore"}

# Display names for canonical service IDs
DISPLAY_NAMES = {
    "account": "Account",
    "acm": "ACM",
    "acmpca": "ACM PCA",
    "amp": "AMP",
    "amplify": "Amplify",
    "apigateway": "API Gateway v1",
    "apigatewaymanagementapi": "API Gateway Management",
    "apigatewayv2": "API Gateway v2",
    "appconfig": "AppConfig",
    "appconfigdata": "AppConfig Data",
    "applicationautoscaling": "Application Auto Scaling",
    "appmesh": "App Mesh",
    "appsync": "AppSync",
    "athena": "Athena",
    "autoscaling": "Auto Scaling",
    "backup": "AWS Backup",
    "batch": "Batch",
    "bcm-data-exports": "BCM Data Exports",
    "bedrock": "Bedrock",
    "bedrock-runtime": "Bedrock Runtime",
    "bedrockagent": "Bedrock Agent",
    "budgets": "Budgets",
    "ce": "Cost Explorer",
    "cloudcontrol": "Cloud Control",
    "clouddirectory": "Cloud Directory",
    "cloudformation": "CloudFormation",
    "cloudfront": "CloudFront",
    "cloudhsmv2": "CloudHSM v2",
    "cloudtrail": "CloudTrail",
    "cloudwatch": "CloudWatch",
    "codeartifact": "CodeArtifact",
    "codebuild": "CodeBuild",
    "codecommit": "CodeCommit",
    "codeconnections": "CodeConnections",
    "codedeploy": "CodeDeploy",
    "codepipeline": "CodePipeline",
    "cognito-idp": "Cognito User Pools",
    "cognitoidentity": "Cognito Identity",
    "comprehend": "Comprehend",
    "config": "AWS Config",
    "connect": "Connect",
    "connectcampaigns": "Connect Campaigns",
    "cur": "Cost & Usage Reports",
    "databrew": "DataBrew",
    "datapipeline": "Data Pipeline",
    "datasync": "DataSync",
    "dax": "DAX",
    "directconnect": "Direct Connect",
    "dms": "DMS",
    "docdb": "DocumentDB",
    "ds": "Directory Service",
    "dsql": "DSQL",
    "dynamodb": "DynamoDB",
    "dynamodbstreams": "DynamoDB Streams",
    "ebs": "EBS",
    "ec2": "EC2",
    "ec2instanceconnect": "EC2 Instance Connect",
    "ecr": "ECR",
    "ecs": "ECS",
    "efs": "EFS",
    "eks": "EKS",
    "elasticache": "ElastiCache",
    "elasticbeanstalk": "Elastic Beanstalk",
    "elb": "ELB",
    "elbv2": "ALB/ELBv2",
    "emr": "EMR",
    "emrcontainers": "EMR Containers",
    "emrserverless": "EMR Serverless",
    "es": "Elasticsearch",
    "events": "EventBridge",
    "firehose": "Firehose",
    "fis": "FIS",
    "forecast": "Forecast",
    "fsx": "FSx",
    "glacier": "Glacier",
    "glue": "Glue",
    "greengrass": "Greengrass",
    "guardduty": "GuardDuty",
    "iam": "IAM",
    "identitystore": "Identity Store",
    "inspector2": "Inspector",
    "iot": "IoT",
    "iotdata": "IoT Data",
    "iotwireless": "IoT Wireless",
    "ivs": "IVS",
    "kafka": "MSK (Kafka)",
    "kinesis": "Kinesis",
    "kinesis-video-archived-media": "Kinesis Video Archived Media",
    "kinesisanalyticsv2": "Kinesis Analytics v2",
    "kinesisvideo": "Kinesis Video",
    "kms": "KMS",
    "lakeformation": "Lake Formation",
    "lambda": "Lambda",
    "lexv2models": "Lex v2",
    "logs": "CloudWatch Logs",
    "macie2": "Macie",
    "managedblockchain": "Managed Blockchain",
    "mediaconnect": "MediaConnect",
    "mediaconvert": "MediaConvert",
    "medialive": "MediaLive",
    "mediapackage": "MediaPackage",
    "mediapackagev2": "MediaPackage v2",
    "mediastore": "MediaStore",
    "mediastore-data": "MediaStore Data",
    "memorydb": "MemoryDB",
    "mq": "MQ",
    "mwaa": "MWAA (Airflow)",
    "neptune": "Neptune",
    "networkfirewall": "Network Firewall",
    "networkmanager": "Network Manager",
    "opensearch": "OpenSearch",
    "opensearchserverless": "OpenSearch Serverless",
    "organizations": "Organizations",
    "osis": "OSIS",
    "panorama": "Panorama",
    "personalize": "Personalize",
    "pinpoint": "Pinpoint",
    "pipes": "EventBridge Pipes",
    "polly": "Polly",
    "pricing": "Pricing",
    "quicksight": "QuickSight",
    "ram": "RAM",
    "rds": "RDS",
    "rdsdata": "RDS Data",
    "redshift": "Redshift",
    "redshiftdata": "Redshift Data",
    "rekognition": "Rekognition",
    "resiliencehub": "Resilience Hub",
    "resource-groups": "Resource Groups",
    "route53": "Route 53",
    "route53domains": "Route 53 Domains",
    "route53resolver": "Route 53 Resolver",
    "s3": "S3",
    "s3control": "S3 Control",
    "s3tables": "S3 Tables",
    "s3vectors": "S3 Vectors",
    "sagemaker": "SageMaker",
    "sagemaker-runtime": "SageMaker Runtime",
    "scheduler": "EventBridge Scheduler",
    "sdb": "SimpleDB",
    "secretsmanager": "Secrets Manager",
    "securityhub": "Security Hub",
    "serverlessrepo": "Serverless App Repository",
    "service-quotas": "Service Quotas",
    "servicecatalog": "Service Catalog",
    "servicecatalogappregistry": "Service Catalog App Registry",
    "servicediscovery": "Service Discovery",
    "ses": "SES",
    "sesv2": "SES v2",
    "shield": "Shield",
    "signer": "Signer",
    "sns": "SNS",
    "sqs": "SQS",
    "ssm": "SSM",
    "ssoadmin": "SSO Admin",
    "stepfunctions": "Step Functions",
    "sts": "STS",
    "support": "Support",
    "swf": "SWF",
    "synthetics": "Synthetics",
    "tagging": "Resource Groups Tagging",
    "textract": "Textract",
    "timestreaminfluxdb": "Timestream InfluxDB",
    "timestreamquery": "Timestream Query",
    "timestreamwrite": "Timestream Write",
    "transcribe": "Transcribe",
    "transfer": "Transfer Family",
    "verifiedpermissions": "Verified Permissions",
    "vpclattice": "VPC Lattice",
    "wafv2": "WAF",
    "workspaces": "WorkSpaces",
    "workspacesweb": "WorkSpaces Web",
    "xray": "X-Ray",
}


def normalize(name):
    """Normalize a service name to its canonical form."""
    if name in INTERNAL:
        return None
    return ALIASES.get(name, name)


def normalize_list(services):
    """Normalize a list of service names, removing internals and deduplicating."""
    seen = set()
    result = []
    for s in services:
        canonical = normalize(s)
        if canonical and canonical not in seen:
            seen.add(canonical)
            result.append(canonical)
    return sorted(result)


def to_display_name(canonical):
    """Get display name for a canonical service ID."""
    return DISPLAY_NAMES.get(canonical, canonical)
