SERVICES = [
    {
        "id": "cloud-run",
        "name": "Cloud Run",
        "category": "Compute",
        "description": "Cloud Run is a fully managed compute platform that lets you deploy and scale containerized applications quickly and securely.",
        "useCases": ["Container workloads", "Web apps", "APIs", "Microservices"],
        "pricing": "Pay per vCPU, memory and request",
        "pricingUrl": "https://cloud.google.com/run/pricing",
        "url": "https://cloud.google.com/run",
        "icon": "🚀",
        "news_keywords": ["Cloud Run"],
        "static_limits": [
            {"name": "Max instances", "value": "1,000"},
            {"name": "Max request timeout", "value": "3,600 seconds (60 min)"},
            {"name": "Max vCPU per instance", "value": "8"},
            {"name": "Max memory per instance", "value": "32 GiB"},
            {"name": "Max request body size", "value": "32 MB"},
            {"name": "Max response body size", "value": "32 MB"},
            {"name": "Max concurrent requests per instance", "value": "1,000"},
            {"name": "Container image size", "value": "10 GiB"},
        ],
    },
    {
        "id": "cloud-run-functions",
        "name": "Cloud Run Functions",
        "category": "Compute",
        "description": "Cloud Run Functions is a lightweight, event-driven compute solution that allows you to create small, single-purpose functions that respond to cloud events.",
        "useCases": ["Event processing", "Webhooks", "Data transformation", "IoT backends"],
        "pricing": "Pay per invocation, compute time and networking",
        "pricingUrl": "https://cloud.google.com/functions/pricing",
        "url": "https://cloud.google.com/functions",
        "icon": "⚡",
        "news_keywords": ["Cloud Functions", "Cloud Run functions"],
        "runtimes": [
            {"name": "Node.js 22", "status": "active"},
            {"name": "Node.js 20", "status": "active"},
            {"name": "Node.js 18", "status": "active"},
            {"name": "Python 3.12", "status": "active"},
            {"name": "Python 3.11", "status": "active"},
            {"name": "Python 3.10", "status": "active"},
            {"name": "Go 1.22", "status": "active"},
            {"name": "Go 1.21", "status": "active"},
            {"name": "Java 21", "status": "active"},
            {"name": "Java 17", "status": "active"},
            {"name": "Java 11", "status": "active"},
            {"name": ".NET 8", "status": "active"},
            {"name": ".NET 6", "status": "active"},
            {"name": "Ruby 3.3", "status": "active"},
            {"name": "Ruby 3.2", "status": "active"},
            {"name": "PHP 8.3", "status": "active"},
            {"name": "PHP 8.2", "status": "active"},
        ],
        "static_limits": [
            {"name": "Max function timeout (1st gen)", "value": "540 seconds (9 min)"},
            {"name": "Max function timeout (2nd gen)", "value": "3,600 seconds (60 min)"},
            {"name": "Max memory", "value": "32 GiB"},
            {"name": "Max vCPUs", "value": "8"},
            {"name": "Max request size (HTTP)", "value": "32 MB"},
            {"name": "Max response size (HTTP)", "value": "32 MB"},
            {"name": "Max event size", "value": "512 KB"},
            {"name": "Max concurrent requests per instance", "value": "1,000"},
            {"name": "Max instances", "value": "3,000"},
            {"name": "Deployment size (compressed)", "value": "100 MB"},
            {"name": "Deployment size (uncompressed)", "value": "500 MB"},
        ],
    },
    {
        "id": "firestore",
        "name": "Firestore",
        "category": "Database",
        "description": "Firestore is a fast, fully managed, serverless, cloud-native NoSQL document database that simplifies storing, syncing, and querying data for mobile, web, and IoT apps at global scale.",
        "useCases": ["Mobile/web backends", "Real-time sync", "User profiles", "Game state"],
        "pricing": "Pay per document read, write, delete and storage",
        "pricingUrl": "https://cloud.google.com/firestore/pricing",
        "url": "https://cloud.google.com/firestore",
        "icon": "🔥",
        "news_keywords": ["Firestore"],
        "static_limits": [
            {"name": "Max document size", "value": "1 MiB"},
            {"name": "Max field depth", "value": "20 levels"},
            {"name": "Max indexes per database", "value": "200 composite"},
            {"name": "Max writes per second per database", "value": "10,000"},
            {"name": "Max concurrent connections (mobile/web)", "value": "1,000,000"},
            {"name": "Max subcollection depth", "value": "100"},
        ],
    },
    {
        "id": "bigquery",
        "name": "BigQuery",
        "category": "Analytics",
        "description": "BigQuery is a serverless, highly scalable, and cost-effective multicloud data warehouse designed for business agility.",
        "useCases": ["Data analytics", "Business intelligence", "Machine learning", "Geospatial analysis"],
        "pricing": "Pay per TB scanned (on-demand) or slot-hours (capacity)",
        "pricingUrl": "https://cloud.google.com/bigquery/pricing",
        "url": "https://cloud.google.com/bigquery",
        "icon": "📊",
        "news_keywords": ["BigQuery"],
        "static_limits": [
            {"name": "Max columns per table", "value": "10,000"},
            {"name": "Max row size", "value": "100 MB"},
            {"name": "Max query length", "value": "1 MB (unresolved)"},
            {"name": "Max concurrent queries", "value": "100"},
            {"name": "Max tables per dataset", "value": "Unlimited"},
            {"name": "Max streaming inserts per second per table", "value": "1,000,000 rows"},
            {"name": "Free tier", "value": "1 TB queries + 10 GB storage/month"},
        ],
    },
    {
        "id": "cloud-pubsub",
        "name": "Cloud Pub/Sub",
        "category": "Messaging",
        "description": "Cloud Pub/Sub is a fully managed real-time messaging service that allows you to send and receive messages between independent applications.",
        "useCases": ["Event streaming", "Data integration", "Service decoupling", "Log aggregation"],
        "pricing": "Pay per data volume delivered",
        "pricingUrl": "https://cloud.google.com/pubsub/pricing",
        "url": "https://cloud.google.com/pubsub",
        "icon": "📨",
        "news_keywords": ["Pub/Sub"],
        "static_limits": [
            {"name": "Max message size", "value": "10 MB"},
            {"name": "Max attributes per message", "value": "100"},
            {"name": "Max attribute key size", "value": "256 bytes"},
            {"name": "Max attribute value size", "value": "1,024 bytes"},
            {"name": "Max subscriptions per topic", "value": "10,000"},
            {"name": "Max topics per project", "value": "10,000"},
            {"name": "Message retention", "value": "31 days"},
        ],
    },
    {
        "id": "cloud-tasks",
        "name": "Cloud Tasks",
        "category": "Messaging",
        "description": "Cloud Tasks is a fully managed service that allows you to manage the execution, dispatch, and delivery of a large number of distributed tasks.",
        "useCases": ["Async task execution", "Rate-limited processing", "Deferred work", "Webhook delivery"],
        "pricing": "Pay per million operations",
        "pricingUrl": "https://cloud.google.com/tasks/pricing",
        "url": "https://cloud.google.com/tasks",
        "icon": "📋",
        "news_keywords": ["Cloud Tasks"],
        "static_limits": [
            {"name": "Max task size", "value": "1 MB"},
            {"name": "Max queues per project", "value": "10,000"},
            {"name": "Max tasks per queue", "value": "Unlimited"},
            {"name": "Max dispatch rate per queue", "value": "500/second"},
            {"name": "Max task retention", "value": "31 days"},
            {"name": "Max concurrent dispatches per queue", "value": "5,000"},
        ],
    },
    {
        "id": "cloud-scheduler",
        "name": "Cloud Scheduler",
        "category": "Integration",
        "description": "Cloud Scheduler is a fully managed enterprise-grade cron job scheduler that allows you to schedule virtually any job.",
        "useCases": ["Cron jobs", "Scheduled pipelines", "Periodic triggers", "Batch processing"],
        "pricing": "Pay per job per month",
        "pricingUrl": "https://cloud.google.com/scheduler/pricing",
        "url": "https://cloud.google.com/scheduler",
        "icon": "⏰",
        "news_keywords": ["Cloud Scheduler"],
        "static_limits": [
            {"name": "Max jobs per project", "value": "500"},
            {"name": "Max job body size", "value": "1 MB"},
            {"name": "Min interval", "value": "1 minute"},
            {"name": "Max retry attempts", "value": "5"},
        ],
    },
    {
        "id": "eventarc",
        "name": "Eventarc",
        "category": "Integration",
        "description": "Eventarc lets you build event-driven architectures by routing events from Google services, SaaS, and your own apps to targets like Cloud Run and Workflows.",
        "useCases": ["Event routing", "Audit log triggers", "Pub/Sub integration", "Cross-service events"],
        "pricing": "No additional charge (pay for underlying services)",
        "pricingUrl": "https://cloud.google.com/eventarc/pricing",
        "url": "https://cloud.google.com/eventarc",
        "icon": "⚡",
        "news_keywords": ["Eventarc"],
        "static_limits": [
            {"name": "Max triggers per project per region", "value": "500"},
            {"name": "Max channels per project per region", "value": "100"},
            {"name": "Max event size", "value": "512 KB"},
        ],
    },
    {
        "id": "cloud-storage",
        "name": "Cloud Storage",
        "category": "Storage",
        "description": "Cloud Storage is a managed service for storing unstructured data. It offers global edge-caching and multiple storage classes for any workload.",
        "useCases": ["Object storage", "Data lakes", "Backups", "Static hosting"],
        "pricing": "Pay per GB stored and operations",
        "pricingUrl": "https://cloud.google.com/storage/pricing",
        "url": "https://cloud.google.com/storage",
        "icon": "🪣",
        "news_keywords": ["Cloud Storage"],
        "static_limits": [
            {"name": "Max object size", "value": "5 TiB (single object)"},
            {"name": "Max buckets per project", "value": "Varies (soft limit)"},
            {"name": "Max object write rate per bucket", "value": "1 write/second (same object)"},
            {"name": "Max read rate per object", "value": "No limit"},
            {"name": "Max metadata size per object", "value": "8 KiB"},
            {"name": "Object name max length", "value": "1,024 bytes"},
        ],
    },
    {
        "id": "workflows",
        "name": "Workflows",
        "category": "Integration",
        "description": "Workflows is a fully managed orchestration platform that executes services in an order that you define, combining Cloud Run, Cloud Functions, and APIs.",
        "useCases": ["Service orchestration", "Batch processing", "CI/CD pipelines", "Data pipelines"],
        "pricing": "Pay per step executed",
        "pricingUrl": "https://cloud.google.com/workflows/pricing",
        "url": "https://cloud.google.com/workflows",
        "icon": "🔀",
        "news_keywords": ["Workflows"],
        "static_limits": [
            {"name": "Max execution duration", "value": "1 year"},
            {"name": "Max steps per execution", "value": "Unlimited"},
            {"name": "Max concurrent executions", "value": "10,000"},
            {"name": "Max workflow size", "value": "128 KB (source)"},
            {"name": "Max variable size", "value": "512 KB"},
            {"name": "Max call stack depth", "value": "20"},
        ],
    },
    {
        "id": "api-gateway",
        "name": "API Gateway",
        "category": "Networking",
        "description": "API Gateway enables you to provide secure access to your backend services through a well-defined REST API that is consistent across all of your services.",
        "useCases": ["API management", "Rate limiting", "Authentication", "Backend routing"],
        "pricing": "Pay per million API calls",
        "pricingUrl": "https://cloud.google.com/api-gateway/pricing",
        "url": "https://cloud.google.com/api-gateway",
        "icon": "🌐",
        "news_keywords": ["API Gateway"],
        "static_limits": [
            {"name": "Max request size", "value": "32 MB"},
            {"name": "Max response size", "value": "32 MB"},
            {"name": "Max timeout", "value": "900 seconds (15 min)"},
            {"name": "Max APIs per project", "value": "10"},
            {"name": "Max gateways per API", "value": "3"},
        ],
    },
    {
        "id": "gke",
        "name": "Google Kubernetes Engine",
        "category": "Compute",
        "description": "Google Kubernetes Engine is a managed Kubernetes service for deploying, managing, and scaling containerized applications on Google Cloud infrastructure.",
        "useCases": ["Container orchestration", "Microservices", "CI/CD", "ML workloads"],
        "pricing": "Free control plane (Autopilot) or $0.10/hr (Standard) + compute costs",
        "pricingUrl": "https://cloud.google.com/kubernetes-engine/pricing",
        "url": "https://cloud.google.com/kubernetes-engine",
        "icon": "☸️",
        "news_keywords": ["GKE", "Kubernetes Engine"],
        "static_limits": [
            {"name": "Nodes per cluster", "value": "15,000"},
            {"name": "Pods per node", "value": "256"},
            {"name": "Pods per cluster", "value": "200,000"},
            {"name": "Services per cluster", "value": "10,000"},
            {"name": "Clusters per zone", "value": "50"},
            {"name": "Node pools per cluster", "value": "100"},
        ],
    },
    {
        "id": "cloud-spanner",
        "name": "Cloud Spanner",
        "category": "Database",
        "description": "Cloud Spanner is a fully managed, mission-critical relational database service that offers transactional consistency at global scale, automatic sharding, and high availability.",
        "useCases": ["Global transactions", "Financial systems", "Inventory management", "Gaming leaderboards"],
        "pricing": "Pay per node-hour or processing unit-hour + storage",
        "pricingUrl": "https://cloud.google.com/spanner/pricing",
        "url": "https://cloud.google.com/spanner",
        "icon": "🗄️",
        "news_keywords": ["Cloud Spanner", "Spanner"],
        "static_limits": [
            {"name": "Max row size", "value": "10 MB"},
            {"name": "Max columns per table", "value": "1,024"},
            {"name": "Max databases per instance", "value": "100"},
            {"name": "Max tables per database", "value": "5,000"},
            {"name": "Max indexes per database", "value": "10,000"},
            {"name": "Max storage per node", "value": "4 TiB"},
        ],
    },
    {
        "id": "cloud-run-jobs",
        "name": "Cloud Run Jobs",
        "category": "Compute",
        "description": "Cloud Run Jobs allows you to run containers to completion without serving requests, ideal for batch processing, data transformation, and scheduled tasks.",
        "useCases": ["Batch processing", "Data migration", "Scheduled tasks", "ML training"],
        "pricing": "Pay per vCPU and memory per second",
        "pricingUrl": "https://cloud.google.com/run/pricing",
        "url": "https://cloud.google.com/run/docs/create-jobs",
        "icon": "⚙️",
        "news_keywords": ["Cloud Run jobs"],
        "static_limits": [
            {"name": "Max task timeout", "value": "86,400 seconds (24 hr)"},
            {"name": "Max tasks per job", "value": "10,000"},
            {"name": "Max vCPU per task", "value": "8"},
            {"name": "Max memory per task", "value": "32 GiB"},
            {"name": "Max retries per task", "value": "10"},
            {"name": "Max parallelism", "value": "100"},
        ],
    },
    {
        "id": "memorystore",
        "name": "Memorystore",
        "category": "Database",
        "description": "Memorystore is a fully managed in-memory data store service for Redis and Memcached, providing sub-millisecond data access for caching and real-time analytics.",
        "useCases": ["Caching", "Session management", "Real-time analytics", "Leaderboards"],
        "pricing": "Pay per GB per hour (Redis) or per node per hour",
        "pricingUrl": "https://cloud.google.com/memorystore/pricing",
        "url": "https://cloud.google.com/memorystore",
        "icon": "⚡",
        "news_keywords": ["Memorystore"],
        "static_limits": [
            {"name": "Max instance size (Redis)", "value": "300 GB"},
            {"name": "Max connections (Redis)", "value": "65,000"},
            {"name": "Max instances per project", "value": "Varies by region"},
            {"name": "Max throughput per node", "value": "12 Gbps"},
        ],
    },
    {
        "id": "secret-manager",
        "name": "Secret Manager",
        "category": "Security",
        "description": "Secret Manager is a secure and convenient storage system for API keys, passwords, certificates, and other sensitive data.",
        "useCases": ["API keys", "Database credentials", "Certificates", "Configuration secrets"],
        "pricing": "Pay per secret version per month + access operations",
        "pricingUrl": "https://cloud.google.com/secret-manager/pricing",
        "url": "https://cloud.google.com/secret-manager",
        "icon": "🔑",
        "news_keywords": ["Secret Manager"],
        "static_limits": [
            {"name": "Max secret size", "value": "64 KiB"},
            {"name": "Max secrets per project", "value": "90,000"},
            {"name": "Max versions per secret", "value": "Unlimited"},
            {"name": "Max labels per secret", "value": "64"},
        ],
    },
    {
        "id": "cloud-build",
        "name": "Cloud Build",
        "category": "DevOps",
        "description": "Cloud Build is a serverless CI/CD platform that lets you build, test, and deploy software quickly across all languages and frameworks.",
        "useCases": ["CI/CD pipelines", "Container builds", "Automated testing", "Deployment automation"],
        "pricing": "Pay per build-minute",
        "pricingUrl": "https://cloud.google.com/build/pricing",
        "url": "https://cloud.google.com/build",
        "icon": "🛠️",
        "news_keywords": ["Cloud Build"],
        "static_limits": [
            {"name": "Max concurrent builds", "value": "30"},
            {"name": "Max build timeout", "value": "86,400 seconds (24 hr)"},
            {"name": "Max build steps", "value": "100"},
            {"name": "Max log size", "value": "16 MB"},
        ],
    },
    {
        "id": "vertex-ai",
        "name": "Vertex AI",
        "category": "AI/ML",
        "description": "Vertex AI is a fully managed ML platform that helps you build, deploy, and scale ML models and AI applications with pre-trained and custom models.",
        "useCases": ["ML model training", "Generative AI", "Predictions", "AutoML"],
        "pricing": "Pay per prediction, training hour, or token (Gemini)",
        "pricingUrl": "https://cloud.google.com/vertex-ai/pricing",
        "url": "https://cloud.google.com/vertex-ai",
        "icon": "🧠",
        "news_keywords": ["Vertex AI", "Gemini"],
        "static_limits": [
            {"name": "Max model size", "value": "10 GB"},
            {"name": "Max prediction request size", "value": "1.5 MB"},
            {"name": "Max concurrent predictions", "value": "Varies by model"},
            {"name": "Max endpoints per project", "value": "1,000"},
        ],
    },
]

DISABLED_SERVICES = []
