CATEGORIES = [
    {
        "id": "functions",
        "name": "Functions",
        "icon": "⚡",
        "services": {"aws": "lambda", "gcp": "cloud-run-functions", "azure": "azure-functions", "stackit": None},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html",
            "gcp": "https://cloud.google.com/functions/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale",
            "stackit": None,
        },
        "limits": [
            {"label": "Max timeout", "aws": "Function timeout", "gcp": "Max function timeout (2nd gen)", "azure": "Max execution time (Consumption)", "stackit": None},
            {"label": "Max memory", "aws": "Function memory allocation", "gcp": "Max memory", "azure": "Max memory (Consumption)", "stackit": None},
            {"label": "Max payload/request size", "aws": "Synchronous payload", "gcp": "Max request size (HTTP)", "azure": "HTTP request size", "stackit": None},
            {"label": "Deployment size", "aws": "Deployment package (.zip file archive) size", "gcp": "Deployment size (compressed)", "azure": "Storage (Consumption)", "stackit": None},
            {"label": "Concurrent executions", "aws": "Concurrent executions", "gcp": "Max concurrent requests per instance", "azure": "Max concurrent HTTP requests", "stackit": None},
        ],
        "pricing": [
            {"label": "Invocations", "aws": "Requests", "gcp": "Invocations", "azure": None, "azure_static": "$0.20 per 1M executions", "stackit": None},
            {"label": "Compute", "aws": "Compute (x86)", "gcp": "Compute (GHz-second)", "azure": None, "azure_static": "$0.000016 per GB-second", "stackit": None},
        ],
    },
    {
        "id": "kubernetes",
        "name": "Kubernetes",
        "icon": "☸️",
        "services": {"aws": "eks", "gcp": "gke", "azure": "aks", "stackit": "kubernetes-engine"},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/eks/latest/userguide/service-quotas.html",
            "gcp": "https://cloud.google.com/kubernetes-engine/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/aks/quotas-skus-regions",
            "stackit": "https://docs.stackit.cloud/stackit/en/kubernetes-engine-ske-75137705.html",
        },
        "limits": [
            {"label": "Nodes per cluster", "aws": "Nodes per cluster", "gcp": "Nodes per cluster", "azure": "Nodes per cluster", "stackit": "Max nodes per cluster"},
            {"label": "Pods per node", "aws": "Pods per node (max)", "gcp": "Pods per node", "azure": "Pods per node", "stackit": None},
            {"label": "Services per cluster", "aws": "Services per cluster", "gcp": "Services per cluster", "azure": "Services per cluster", "stackit": None},
            {"label": "Node pools per cluster", "aws": "Managed node groups per cluster", "gcp": "Node pools per cluster", "azure": "Max node pools per cluster", "stackit": None},
            {"label": "Clusters", "aws": "Clusters", "gcp": "Clusters per zone", "azure": "Max clusters per subscription", "stackit": "Max clusters per project"},
        ],
        "pricing": [
            {"label": "Cluster management", "aws": None, "gcp": None, "azure": None, "aws_static": "$0.10 per cluster/hour", "gcp_static": "$0.10 per cluster/hour", "azure_static": "Free", "stackit": None, "stackit_static": "€0.10 per cluster/hour"},
        ],
    },
    {
        "id": "nosql",
        "name": "NoSQL Database",
        "icon": "🗄️",
        "services": {"aws": "dynamodb", "gcp": "firestore", "azure": "cosmos-db", "stackit": "mongodb-flex"},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html",
            "gcp": "https://cloud.google.com/firestore/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits",
            "stackit": "https://docs.stackit.cloud/stackit/en/mongodb-flex-75137705.html",
        },
        "limits": [
            {"label": "Max document/item size", "aws": None, "gcp": "Max document size", "azure": "Max document size", "stackit": None, "aws_static": "400 KB"},
            {"label": "Secondary indexes", "aws": "Global Secondary Indexes per table", "gcp": "Max indexes per database", "azure": None, "stackit": None},
            {"label": "Max storage", "aws": None, "gcp": None, "azure": None, "stackit": "Max storage"},
            {"label": "Replica sets", "aws": None, "gcp": None, "azure": None, "stackit": "Replica sets"},
        ],
        "pricing": [
            {"label": "Writes", "aws": "Write Requests (on-demand)", "gcp": "Document writes", "azure": None, "azure_static": "$0.25 per 1M RUs", "stackit": None, "stackit_static": "€0.12 per hour (1.2 vCPU single)"},
            {"label": "Reads", "aws": "Read Requests (on-demand)", "gcp": "Document reads", "azure": None, "azure_static": "$0.25 per 1M RUs", "stackit": None},
            {"label": "Storage", "aws": "Storage (Standard)", "gcp": "Storage", "azure": None, "azure_static": "$0.25 per GB/month", "stackit": None},
        ],
    },
    {
        "id": "object-storage",
        "name": "Object Storage",
        "icon": "📦",
        "services": {"aws": "s3", "gcp": "cloud-storage", "azure": "blob-storage", "stackit": "object-storage"},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html",
            "gcp": "https://cloud.google.com/storage/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#azure-blob-storage-limits",
            "stackit": "https://docs.stackit.cloud/stackit/en/object-storage-75137705.html",
        },
        "limits": [
            {"label": "Max object size", "aws": "Object size", "gcp": "Max object size", "azure": "Max blob size (block blob)", "stackit": "Max object size"},
            {"label": "S3 compatibility", "aws": None, "gcp": None, "azure": None, "stackit": "S3 compatibility"},
        ],
        "pricing": [
            {"label": "Storage (standard)", "aws": None, "gcp": "Standard storage", "azure": None, "aws_static": "$0.023 per GB/month", "azure_static": "$0.018 per GB/month", "stackit": None, "stackit_static": "€0.027 per GB/month"},
            {"label": "Write operations", "aws": None, "gcp": "Class A operations", "azure": None, "aws_static": "$0.005 per 1K PUT", "azure_static": "$0.055 per 10K ops", "stackit": None},
            {"label": "Read operations", "aws": None, "gcp": "Class B operations", "azure": None, "aws_static": "$0.0004 per 1K GET", "azure_static": "$0.0044 per 10K ops", "stackit": None},
        ],
    },
    {
        "id": "messaging",
        "name": "Messaging",
        "icon": "📨",
        "services": {"aws": "sqs", "gcp": "cloud-pubsub", "azure": "service-bus", "stackit": "rabbitmq"},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-quotas.html",
            "gcp": "https://cloud.google.com/pubsub/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas",
            "stackit": "https://docs.stackit.cloud/stackit/en/rabbitmq-75137705.html",
        },
        "limits": [
            {"label": "Max message size", "aws": "Message Size", "gcp": "Max message size", "azure": "Max message size (Standard)", "stackit": None},
            {"label": "Message retention", "aws": "Message retention", "gcp": "Message retention", "azure": "Message retention", "stackit": None},
            {"label": "High availability", "aws": None, "gcp": None, "azure": None, "stackit": "High availability"},
            {"label": "Protocols", "aws": None, "gcp": None, "azure": None, "stackit": "Protocols"},
        ],
        "pricing": [
            {"label": "Operations", "aws": "Standard Queue", "gcp": "Message delivery", "azure": None, "azure_static": "$0.05 per 1M operations", "stackit": None, "stackit_static": "€0.20 per hour (1.2 vCPU replica)"},
        ],
    },
    {
        "id": "events",
        "name": "Events",
        "icon": "📡",
        "services": {"aws": "eventbridge", "gcp": "eventarc", "azure": "event-grid", "stackit": None},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-quota.html",
            "gcp": "https://cloud.google.com/eventarc/docs/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/event-grid/quotas-limits",
            "stackit": None,
        },
        "limits": [
            {"label": "Max event size", "aws": "Event size", "gcp": "Max event size", "azure": "Max event size", "stackit": None},
            {"label": "Max rules/triggers", "aws": "Rules per event bus", "gcp": "Max triggers per project per region", "azure": "Max event subscriptions per topic", "stackit": None},
            {"label": "Targets per rule", "aws": "Targets per rule", "gcp": None, "azure": None, "stackit": None},
        ],
        "pricing": [
            {"label": "Events/operations", "aws": "Custom Events", "gcp": None, "azure": None, "azure_static": "$0.60 per 1M operations", "stackit": None},
        ],
    },
    {
        "id": "api-gateway",
        "name": "API Gateway",
        "icon": "🔗",
        "services": {"aws": "api-gateway", "gcp": "api-gateway", "azure": "api-management", "stackit": None},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html",
            "gcp": "https://cloud.google.com/api-gateway/docs/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/api-management/api-management-capacity",
            "stackit": None,
        },
        "limits": [
            {"label": "Max payload size", "aws": "API Payload Size", "gcp": "Max request size", "azure": "Max request size", "stackit": None},
            {"label": "Max timeout", "aws": "Maximum integration timeout in milliseconds", "gcp": "Max timeout", "azure": "Max request timeout", "stackit": None},
            {"label": "Throttle rate", "aws": "Throttle rate", "gcp": None, "azure": None, "stackit": None},
            {"label": "Max APIs", "aws": "Regional APIs", "gcp": "Max APIs per project", "azure": "Max APIs", "stackit": None},
        ],
        "pricing": [
            {"label": "API calls", "aws": "REST API Requests", "gcp": "API calls", "azure": None, "azure_static": "$3.50 per 1M calls (Consumption)", "stackit": None},
        ],
    },
    {
        "id": "secrets",
        "name": "Secrets Management",
        "icon": "🔑",
        "services": {"aws": "secrets-manager", "gcp": "secret-manager", "azure": "key-vault", "stackit": "secrets-manager"},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_limits.html",
            "gcp": "https://cloud.google.com/secret-manager/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/key-vault/general/service-limits",
            "stackit": "https://docs.stackit.cloud/stackit/en/secrets-manager-75137705.html",
        },
        "limits": [
            {"label": "Max secret size", "aws": "Secret value size", "gcp": "Max secret size", "azure": "Max secret size", "stackit": None},
            {"label": "Max secrets per account", "aws": "Secrets per account", "gcp": "Max secrets per project", "azure": None, "stackit": None},
            {"label": "Max versions per secret", "aws": "Versions per secret", "gcp": "Max versions per secret", "azure": None, "stackit": None},
            {"label": "Audit log", "aws": None, "gcp": None, "azure": None, "stackit": "Audit log"},
        ],
        "pricing": [
            {"label": "Storage/operations", "aws": None, "gcp": "Active secret versions", "azure": None, "aws_static": "$0.40 per secret/month", "azure_static": "$0.03 per 10K operations", "stackit": None, "stackit_static": "€0.000139 per version/hour"},
            {"label": "Access operations", "aws": None, "gcp": "Access operations", "azure": None, "aws_static": "$0.05 per 10K API calls", "azure_static": "$0.03 per 10K operations", "stackit": None},
        ],
    },
    {
        "id": "ai-ml",
        "name": "AI / ML",
        "icon": "🧠",
        "services": {"aws": "bedrock", "gcp": "vertex-ai", "azure": "azure-ai-services", "stackit": "ai-model-serving"},
        "limitsUrls": {
            "aws": "https://docs.aws.amazon.com/bedrock/latest/userguide/quotas.html",
            "gcp": "https://cloud.google.com/vertex-ai/docs/quotas",
            "azure": "https://learn.microsoft.com/en-us/azure/ai-services/openai/quotas-limits",
            "stackit": "https://docs.stackit.cloud/stackit/en/ai-model-serving-75137705.html",
        },
        "limits": [
            {"label": "Max input tokens", "aws": "Max input tokens", "gcp": None, "azure": "Max tokens per request", "stackit": None},
            {"label": "API compatibility", "aws": None, "gcp": None, "azure": None, "stackit": "API compatibility"},
            {"label": "Infrastructure", "aws": None, "gcp": None, "azure": None, "stackit": "Infrastructure"},
        ],
        "pricing": [
            {"label": "Input tokens (LLM)", "aws": None, "gcp": "Gemini 1.5 Flash input", "azure": None, "aws_static": "$0.003 per 1K tokens (Claude Haiku)", "azure_static": "$2.50 per 1M tokens (GPT-4o)", "stackit": None, "stackit_static": "€0.45 per 1M tokens (LLM plus)"},
            {"label": "Output tokens (LLM)", "aws": None, "gcp": "Gemini 1.5 Flash output", "azure": None, "aws_static": "$0.015 per 1K tokens (Claude Haiku)", "azure_static": "$10.00 per 1M tokens (GPT-4o)", "stackit": None, "stackit_static": "€0.45 per 1M tokens (LLM plus)"},
        ],
    },
]
