SERVICES = [
    {
        "id": "azure-functions",
        "name": "Azure Functions",
        "category": "Compute",
        "description": "Azure Functions is an event-driven, serverless compute platform that helps you develop more efficiently using the programming language of your choice.",
        "useCases": ["APIs", "Event processing", "Scheduled tasks", "Microservices"],
        "pricing": "Pay per execution, execution time and memory",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/functions/",
        "url": "https://azure.microsoft.com/en-us/products/functions",
        "icon": "⚡",
        "runtimes": [
            {"name": "Node.js 20", "status": "active"},
            {"name": "Node.js 18", "status": "active"},
            {"name": "Python 3.11", "status": "active"},
            {"name": "Python 3.10", "status": "active"},
            {"name": "Python 3.9", "status": "active"},
            {"name": "Java 21", "status": "active"},
            {"name": "Java 17", "status": "active"},
            {"name": "Java 11", "status": "active"},
            {"name": ".NET 8 (isolated)", "status": "active"},
            {"name": ".NET 6 (in-process)", "status": "deprecated"},
            {"name": "PowerShell 7.4", "status": "active"},
            {"name": "TypeScript", "status": "active"},
        ],
        "static_limits": [
            {"name": "Max execution time (Consumption)", "value": "10 minutes"},
            {"name": "Max execution time (Premium/Dedicated)", "value": "Unlimited"},
            {"name": "Max memory (Consumption)", "value": "1.5 GB"},
            {"name": "Max instances (Consumption)", "value": "200"},
            {"name": "Max instances (Premium)", "value": "100"},
            {"name": "HTTP request size", "value": "100 MB"},
            {"name": "Max concurrent HTTP requests", "value": "Unlimited"},
            {"name": "Storage (Consumption)", "value": "1 GB"},
            {"name": "Storage (Premium)", "value": "250 GB"},
        ],
    },
    {
        "id": "container-apps",
        "name": "Azure Container Apps",
        "category": "Compute",
        "description": "Azure Container Apps is a fully managed serverless container service for building and deploying modern apps at scale.",
        "useCases": ["Microservices", "Web apps", "APIs", "Background processing"],
        "pricing": "Pay per vCPU and memory per second",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/container-apps/",
        "url": "https://azure.microsoft.com/en-us/products/container-apps",
        "icon": "🐳",
        "static_limits": [
            {"name": "Max vCPU per container", "value": "4"},
            {"name": "Max memory per container", "value": "8 GiB"},
            {"name": "Max replicas", "value": "300"},
            {"name": "Max apps per environment", "value": "100"},
            {"name": "Max environments per subscription", "value": "15"},
            {"name": "Max container image size", "value": "8 GB"},
            {"name": "Request timeout", "value": "240 seconds"},
        ],
    },
    {
        "id": "cosmos-db",
        "name": "Azure Cosmos DB",
        "category": "Database",
        "description": "Azure Cosmos DB is a fully managed, globally distributed, multi-model NoSQL database service for building highly responsive and scalable applications.",
        "useCases": ["Global apps", "Real-time analytics", "IoT", "Personalization"],
        "pricing": "Pay per RU/s provisioned or consumed (serverless)",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/cosmos-db/",
        "url": "https://azure.microsoft.com/en-us/products/cosmos-db",
        "icon": "🌍",
        "static_limits": [
            {"name": "Max document size", "value": "2 MB"},
            {"name": "Max RU/s per container (provisioned)", "value": "Unlimited (partitioned)"},
            {"name": "Max RU/s per request (serverless)", "value": "5,000"},
            {"name": "Max storage per container", "value": "Unlimited (partitioned)"},
            {"name": "Max throughput (serverless)", "value": "5,000 RU/s burst"},
            {"name": "Max storage (serverless)", "value": "1 TB"},
            {"name": "Max regions", "value": "Unlimited"},
        ],
    },
    {
        "id": "service-bus",
        "name": "Azure Service Bus",
        "category": "Messaging",
        "description": "Azure Service Bus is a fully managed enterprise message broker with message queues and publish-subscribe topics for decoupling applications.",
        "useCases": ["Decoupling services", "Load leveling", "Ordered messaging", "Transactions"],
        "pricing": "Pay per million operations and brokered connections",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/service-bus/",
        "url": "https://azure.microsoft.com/en-us/products/service-bus",
        "icon": "📨",
        "static_limits": [
            {"name": "Max message size (Standard)", "value": "256 KB"},
            {"name": "Max message size (Premium)", "value": "100 MB"},
            {"name": "Max queue/topic size", "value": "80 GB"},
            {"name": "Max queues/topics per namespace", "value": "10,000"},
            {"name": "Max subscriptions per topic", "value": "2,000"},
            {"name": "Max concurrent connections", "value": "5,000"},
            {"name": "Message retention", "value": "Up to 90 days"},
        ],
    },
    {
        "id": "event-grid",
        "name": "Azure Event Grid",
        "category": "Integration",
        "description": "Azure Event Grid is a fully managed event routing service that enables uniform event consumption using a publish-subscribe model.",
        "useCases": ["Event-driven architectures", "Serverless triggers", "Automation", "Application integration"],
        "pricing": "Pay per million operations",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/event-grid/",
        "url": "https://azure.microsoft.com/en-us/products/event-grid",
        "icon": "⚡",
        "static_limits": [
            {"name": "Max event size", "value": "1 MB"},
            {"name": "Max batch size", "value": "1 MB"},
            {"name": "Max events per batch", "value": "5,000"},
            {"name": "Max event subscriptions per topic", "value": "500"},
            {"name": "Max custom topics per subscription", "value": "100"},
            {"name": "Max throughput per topic", "value": "5,000 events/second"},
            {"name": "Event retention", "value": "24 hours"},
        ],
    },
    {
        "id": "event-hubs",
        "name": "Azure Event Hubs",
        "category": "Streaming",
        "description": "Azure Event Hubs is a big data streaming platform and event ingestion service capable of receiving and processing millions of events per second.",
        "useCases": ["Telemetry streaming", "Log aggregation", "Real-time analytics", "Event sourcing"],
        "pricing": "Pay per throughput unit and ingress events",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/event-hubs/",
        "url": "https://azure.microsoft.com/en-us/products/event-hubs",
        "icon": "🌊",
        "static_limits": [
            {"name": "Max event size", "value": "1 MB"},
            {"name": "Max throughput units (Standard)", "value": "40"},
            {"name": "Max processing units (Premium)", "value": "16"},
            {"name": "Max partitions (Standard)", "value": "32"},
            {"name": "Max partitions (Dedicated)", "value": "2,048"},
            {"name": "Max retention (Standard)", "value": "7 days"},
            {"name": "Max retention (Premium/Dedicated)", "value": "90 days"},
            {"name": "Max consumer groups (Standard)", "value": "20"},
        ],
    },
    {
        "id": "logic-apps",
        "name": "Azure Logic Apps",
        "category": "Integration",
        "description": "Azure Logic Apps is a cloud platform for creating and running automated workflows that integrate your apps, data, services, and systems.",
        "useCases": ["Workflow automation", "B2B integration", "SaaS connectivity", "Data orchestration"],
        "pricing": "Pay per action execution and connector usage",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/logic-apps/",
        "url": "https://azure.microsoft.com/en-us/products/logic-apps",
        "icon": "🔀",
        "static_limits": [
            {"name": "Max workflow run duration", "value": "90 days"},
            {"name": "Max actions per workflow", "value": "500"},
            {"name": "Max nesting depth", "value": "8 levels"},
            {"name": "Max concurrent runs", "value": "250"},
            {"name": "Max message size", "value": "100 MB"},
            {"name": "Max expression characters", "value": "8,192"},
            {"name": "Max workflows per subscription per region", "value": "1,000"},
        ],
    },
    {
        "id": "api-management",
        "name": "Azure API Management",
        "category": "Networking",
        "description": "Azure API Management is a hybrid, multi-cloud management platform for APIs across all environments, enabling secure and productive API programs.",
        "useCases": ["API gateway", "Developer portal", "Rate limiting", "API versioning"],
        "pricing": "Pay per unit (Consumption: per 10K calls)",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/api-management/",
        "url": "https://azure.microsoft.com/en-us/products/api-management",
        "icon": "🌐",
        "static_limits": [
            {"name": "Max request size", "value": "4 MB (Consumption)"},
            {"name": "Max response size", "value": "2 MB (Consumption)"},
            {"name": "Max APIs", "value": "50 (Consumption)"},
            {"name": "Max operations per API", "value": "1,000"},
            {"name": "Max subscriptions", "value": "500 (Consumption)"},
            {"name": "Max request timeout", "value": "120 seconds"},
            {"name": "Max policy size", "value": "256 KB"},
        ],
    },
    {
        "id": "blob-storage",
        "name": "Azure Blob Storage",
        "category": "Storage",
        "description": "Azure Blob Storage is a massively scalable and secure object storage for cloud-native workloads, archives, data lakes, and high-performance computing.",
        "useCases": ["Data lakes", "Backups", "Static content", "Big data analytics"],
        "pricing": "Pay per GB stored and operations",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/storage/blobs/",
        "url": "https://azure.microsoft.com/en-us/products/storage/blobs",
        "icon": "📦",
        "static_limits": [
            {"name": "Max blob size (block blob)", "value": "190.7 TiB (50K blocks x 4 GiB)"},
            {"name": "Max block size", "value": "4,000 MiB"},
            {"name": "Max blocks per blob", "value": "50,000"},
            {"name": "Max storage account capacity", "value": "5 PiB"},
            {"name": "Max request rate per storage account", "value": "20,000 requests/second"},
            {"name": "Max egress per storage account", "value": "50 Gbps"},
        ],
    },
    {
        "id": "queue-storage",
        "name": "Azure Queue Storage",
        "category": "Messaging",
        "description": "Azure Queue Storage is a service for storing large numbers of messages that can be accessed from anywhere via authenticated HTTP or HTTPS calls.",
        "useCases": ["Async processing", "Work queues", "Decoupling components", "Load buffering"],
        "pricing": "Pay per 10K operations and storage",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/storage/queues/",
        "url": "https://azure.microsoft.com/en-us/products/storage/queues",
        "icon": "📋",
        "static_limits": [
            {"name": "Max message size", "value": "64 KB"},
            {"name": "Max queue size", "value": "Unlimited"},
            {"name": "Max message TTL", "value": "7 days (or unlimited)"},
            {"name": "Max visibility timeout", "value": "7 days"},
            {"name": "Max messages per peek", "value": "32"},
            {"name": "Target throughput per queue", "value": "2,000 messages/second"},
        ],
    },
    {
        "id": "signalr",
        "name": "Azure SignalR Service",
        "category": "Real-time",
        "description": "Azure SignalR Service is a fully managed service for adding real-time web functionality to applications, enabling server-to-client push content instantly.",
        "useCases": ["Live dashboards", "Chat apps", "Notifications", "Collaborative editing"],
        "pricing": "Pay per unit and messages (serverless mode)",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/signalr-service/",
        "url": "https://azure.microsoft.com/en-us/products/signalr-service",
        "icon": "📡",
        "static_limits": [
            {"name": "Max connections per unit (Standard)", "value": "1,000"},
            {"name": "Max messages per unit per day (Free)", "value": "20,000"},
            {"name": "Max message size", "value": "1 MB"},
            {"name": "Max units", "value": "100"},
            {"name": "Max groups per connection", "value": "Unlimited"},
        ],
    },
    {
        "id": "static-web-apps",
        "name": "Azure Static Web Apps",
        "category": "Compute",
        "description": "Azure Static Web Apps is a service that automatically builds and deploys full-stack web apps from a code repository to Azure.",
        "useCases": ["SPAs", "Static sites", "JAMstack", "Serverless APIs"],
        "pricing": "Free tier available; Standard plan per app/month",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/app-service/static/",
        "url": "https://azure.microsoft.com/en-us/products/app-service/static",
        "icon": "🌐",
        "static_limits": [
            {"name": "Max app size (Free)", "value": "250 MB"},
            {"name": "Max app size (Standard)", "value": "500 MB"},
            {"name": "Max custom domains (Free)", "value": "2"},
            {"name": "Max custom domains (Standard)", "value": "5"},
            {"name": "Max API functions", "value": "Managed Functions or bring your own"},
            {"name": "Bandwidth (Free)", "value": "100 GB/month"},
            {"name": "Max staging environments (Standard)", "value": "10"},
        ],
    },
    {
        "id": "aks",
        "name": "Azure Kubernetes Service",
        "category": "Compute",
        "description": "Azure Kubernetes Service is a managed Kubernetes service for deploying, managing, and scaling containerized applications with integrated CI/CD and enterprise-grade security.",
        "useCases": ["Container orchestration", "Microservices", "DevOps", "ML workloads"],
        "pricing": "Free control plane + compute costs (Standard tier: $0.10/cluster/hour)",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/kubernetes-service/",
        "url": "https://azure.microsoft.com/en-us/products/kubernetes-service",
        "icon": "☸️",
        "static_limits": [
            {"name": "Nodes per cluster", "value": "5,000"},
            {"name": "Pods per node", "value": "250"},
            {"name": "Max clusters per subscription", "value": "5,000"},
            {"name": "Max node pools per cluster", "value": "100"},
            {"name": "Max pods per cluster", "value": "200,000"},
            {"name": "Services per cluster", "value": "5,000"},
        ],
    },
    {
        "id": "azure-sql-serverless",
        "name": "Azure SQL Serverless",
        "category": "Database",
        "description": "Azure SQL Database serverless is a compute tier that automatically scales compute based on workload demand and bills for compute used per second.",
        "useCases": ["Intermittent workloads", "Dev/test", "Variable usage apps", "Multi-tenant SaaS"],
        "pricing": "Pay per vCore-second + storage",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/azure-sql-database/single/",
        "url": "https://azure.microsoft.com/en-us/products/azure-sql/database",
        "icon": "🗄️",
        "static_limits": [
            {"name": "Max vCores", "value": "80"},
            {"name": "Min vCores", "value": "0.5"},
            {"name": "Max storage", "value": "4 TB"},
            {"name": "Auto-pause delay", "value": "1 hour minimum"},
            {"name": "Max database size", "value": "4 TB"},
            {"name": "Max concurrent workers", "value": "1,600 (at 80 vCores)"},
        ],
    },
    {
        "id": "azure-ai-services",
        "name": "Azure AI Services",
        "category": "AI/ML",
        "description": "Azure AI Services provides pre-built and customizable AI models and APIs for vision, speech, language, and decision-making capabilities.",
        "useCases": ["Text generation", "Speech recognition", "Computer vision", "Language understanding"],
        "pricing": "Pay per transaction or token",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/cognitive-services/",
        "url": "https://azure.microsoft.com/en-us/products/ai-services",
        "icon": "🧠",
        "static_limits": [
            {"name": "Max requests per minute (GPT-4o)", "value": "Varies by deployment"},
            {"name": "Max tokens per request", "value": "128,000 (GPT-4o)"},
            {"name": "Max concurrent requests", "value": "Varies by tier"},
            {"name": "Max custom models per resource", "value": "50"},
        ],
    },
    {
        "id": "key-vault",
        "name": "Azure Key Vault",
        "category": "Security",
        "description": "Azure Key Vault is a cloud service for securely storing and accessing secrets, keys, and certificates.",
        "useCases": ["Secret management", "Key management", "Certificate management", "Encryption"],
        "pricing": "Pay per operation and key/secret stored",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/key-vault/",
        "url": "https://azure.microsoft.com/en-us/products/key-vault",
        "icon": "🔑",
        "static_limits": [
            {"name": "Max secret size", "value": "25 KB"},
            {"name": "Max transactions per 10 seconds", "value": "4,000"},
            {"name": "Max keys per vault", "value": "Unlimited"},
            {"name": "Max vaults per subscription per region", "value": "400"},
        ],
    },
    {
        "id": "notification-hubs",
        "name": "Azure Notification Hubs",
        "category": "Messaging",
        "description": "Azure Notification Hubs is a massively scalable push notification engine for quickly sending millions of notifications to iOS, Android, Windows, or any backend.",
        "useCases": ["Push notifications", "Breaking news", "Marketing campaigns", "Location-based alerts"],
        "pricing": "Pay per namespace tier + pushes",
        "pricingUrl": "https://azure.microsoft.com/en-us/pricing/details/notification-hubs/",
        "url": "https://azure.microsoft.com/en-us/products/notification-hubs",
        "icon": "🔔",
        "static_limits": [
            {"name": "Max pushes per day (Free)", "value": "1,000,000"},
            {"name": "Max active devices (Basic)", "value": "200,000"},
            {"name": "Max active devices (Standard)", "value": "10,000,000"},
            {"name": "Max payload size", "value": "64 KB"},
        ],
    },
]

DISABLED_SERVICES = []
