SERVICES = [
    {
        "id": "lambda",
        "name": "AWS Lambda",
        "category": "Compute",
        "service_code": "lambda",
        "description": "Run code without provisioning or managing servers. Pay only for the compute time you consume.",
        "useCases": ["APIs", "Event processing", "Data transformation", "Scheduled tasks"],
        "pricing": "Pay per request and compute duration",
        "url": "https://aws.amazon.com/lambda/",
        "icon": "⚡",
        "news_keywords": ["Lambda"],
        "static_limits": [
            {"name": "Memory", "value": "128 MB – 10,240 MB"},
            {"name": "Timeout", "value": "900 seconds (15 min)"},
            {"name": "Package size (zip)", "value": "50 MB compressed, 250 MB uncompressed"},
            {"name": "Container image size", "value": "10 GB"},
            {"name": "Ephemeral storage (/tmp)", "value": "512 MB – 10,240 MB"},
            {"name": "Payload (sync)", "value": "6 MB"},
            {"name": "Payload (async)", "value": "256 KB"},
            {"name": "Environment variables", "value": "4 KB total"},
        ],
        "runtimes": [
            {"name": "Node.js 22", "status": "active", "eol": "2027-04-30"},
            {"name": "Node.js 20", "status": "active", "eol": "2026-04-30"},
            {"name": "Python 3.13", "status": "active", "eol": "2029-10-01"},
            {"name": "Python 3.12", "status": "active", "eol": "2028-10-01"},
            {"name": "Java 21", "status": "active", "eol": "2028-09-01"},
            {"name": "Java 17", "status": "active", "eol": "2027-09-01"},
            {"name": ".NET 8", "status": "active", "eol": "2026-11-10"},
            {"name": "Ruby 3.3", "status": "active", "eol": "2027-03-31"},
            {"name": "Go (provided.al2023)", "status": "active"},
            {"name": "Rust (provided.al2023)", "status": "active"},
            {"name": "Node.js 18", "status": "deprecated", "eol": "2025-04-30"},
            {"name": "Python 3.9", "status": "deprecated", "eol": "2025-10-01"},
            {"name": "Java 11", "status": "deprecated", "eol": "2025-01-01"},
        ],
    },
    {
        "id": "dynamodb",
        "name": "Amazon DynamoDB",
        "category": "Database",
        "service_code": "dynamodb",
        "description": "Fast, flexible NoSQL database service for single-digit millisecond performance at any scale.",
        "useCases": ["Key-value store", "Session management", "Real-time analytics", "IoT data"],
        "pricing": "Pay per read/write capacity unit or on-demand",
        "url": "https://aws.amazon.com/dynamodb/",
        "icon": "🗄️",
        "news_keywords": ["DynamoDB"],
        "static_limits": [
            {"name": "Item size", "value": "400 KB"},
            {"name": "Partition key length", "value": "2048 bytes"},
            {"name": "Sort key length", "value": "1024 bytes"},
            {"name": "GSIs per table", "value": "20"},
            {"name": "LSIs per table", "value": "5"},
            {"name": "Projected attributes per index", "value": "100"},
        ],
    },
    {
        "id": "sqs",
        "name": "Amazon SQS",
        "category": "Integration",
        "service_code": "sqs",
        "description": "Fully managed message queuing service to decouple and scale microservices.",
        "useCases": ["Message queuing", "Decoupling services", "Buffering", "Batch processing"],
        "pricing": "Pay per million requests",
        "url": "https://aws.amazon.com/sqs/",
        "icon": "📬",
        "news_keywords": ["SQS", "Simple Queue Service"],
        "static_limits": [
            {"name": "Message size", "value": "256 KB"},
            {"name": "Message retention", "value": "1 min – 14 days"},
            {"name": "Visibility timeout", "value": "0 s – 12 hours"},
            {"name": "Long poll wait", "value": "0 – 20 seconds"},
            {"name": "Batch size", "value": "10 messages"},
            {"name": "In-flight (standard)", "value": "120,000"},
            {"name": "In-flight (FIFO)", "value": "20,000"},
        ],
    },
]

DISABLED_SERVICES = [
    {
        "id": "api-gateway",
        "name": "Amazon API Gateway",
        "category": "Integration",
        "service_code": "apigateway",
        "description": "Create, publish, maintain, monitor, and secure APIs at any scale.",
        "useCases": ["REST APIs", "WebSocket APIs", "HTTP APIs", "API management"],
        "pricing": "Pay per API call and data transfer",
        "url": "https://aws.amazon.com/api-gateway/",
        "icon": "🔗",
        "static_limits": [
            {"name": "Payload size", "value": "10 MB"},
            {"name": "Timeout (REST)", "value": "29 seconds"},
            {"name": "Timeout (HTTP API)", "value": "30 seconds"},
            {"name": "Timeout (WebSocket)", "value": "2 hours idle, 10 min message"},
        ],
    },
    {
        "id": "s3",
        "name": "Amazon S3",
        "category": "Storage",
        "service_code": "s3",
        "description": "Object storage built to retrieve any amount of data from anywhere.",
        "useCases": ["Static hosting", "Data lake", "Backup", "Content distribution"],
        "pricing": "Pay per GB stored and requests",
        "url": "https://aws.amazon.com/s3/",
        "icon": "📦",
        "static_limits": [
            {"name": "Object size", "value": "5 TB"},
            {"name": "PUT/COPY/POST/DELETE", "value": "3,500 req/s per prefix"},
            {"name": "GET/HEAD", "value": "5,500 req/s per prefix"},
            {"name": "Metadata size", "value": "2 KB"},
        ],
    },
    {
        "id": "step-functions",
        "name": "AWS Step Functions",
        "category": "Integration",
        "service_code": "states",
        "description": "Visual workflow service to orchestrate AWS services and build distributed applications.",
        "useCases": ["Workflow orchestration", "ETL pipelines", "Order processing", "ML pipelines"],
        "pricing": "Pay per state transition",
        "url": "https://aws.amazon.com/step-functions/",
        "icon": "🔄",
        "static_limits": [
            {"name": "Max execution time (Standard)", "value": "1 year"},
            {"name": "Max execution time (Express)", "value": "5 minutes"},
            {"name": "Max input/output size", "value": "256 KB"},
            {"name": "Max execution history events", "value": "25,000"},
        ],
    },
    {
        "id": "eventbridge",
        "name": "Amazon EventBridge",
        "category": "Integration",
        "service_code": "events",
        "description": "Serverless event bus that connects applications using events from your apps, SaaS, and AWS services.",
        "useCases": ["Event-driven architecture", "SaaS integration", "Scheduling", "Cross-account events"],
        "pricing": "Pay per event published",
        "url": "https://aws.amazon.com/eventbridge/",
        "icon": "📡",
        "static_limits": [
            {"name": "Event size", "value": "256 KB"},
            {"name": "Rules per event bus", "value": "300"},
            {"name": "Targets per rule", "value": "5"},
            {"name": "Invocation rate", "value": "10,000/s (soft)"},
        ],
    },
    {
        "id": "sns",
        "name": "Amazon SNS",
        "category": "Integration",
        "service_code": "sns",
        "description": "Fully managed pub/sub messaging and mobile notifications service.",
        "useCases": ["Push notifications", "Fan-out patterns", "Alerts", "Email/SMS delivery"],
        "pricing": "Pay per publish and delivery",
        "url": "https://aws.amazon.com/sns/",
        "icon": "📢",
        "static_limits": [
            {"name": "Message size", "value": "256 KB"},
            {"name": "Subscriptions per topic", "value": "12,500,000"},
            {"name": "Topics per account", "value": "100,000"},
            {"name": "Filter policies per account", "value": "200"},
        ],
    },
    {
        "id": "fargate",
        "name": "AWS Fargate",
        "category": "Compute",
        "service_code": "fargate",
        "description": "Serverless compute engine for containers that works with ECS and EKS.",
        "useCases": ["Container workloads", "Microservices", "Batch processing", "CI/CD"],
        "pricing": "Pay per vCPU and memory per second",
        "url": "https://aws.amazon.com/fargate/",
        "icon": "🐳",
        "static_limits": [
            {"name": "vCPU", "value": "0.25 – 16"},
            {"name": "Memory", "value": "0.5 GB – 120 GB"},
            {"name": "Ephemeral storage", "value": "20 GB – 200 GB"},
        ],
    },
    {
        "id": "cognito",
        "name": "Amazon Cognito",
        "category": "Security",
        "service_code": "cognito-idp",
        "description": "Add user sign-up, sign-in, and access control to your web and mobile apps.",
        "useCases": ["User authentication", "Social login", "MFA", "User management"],
        "pricing": "Pay per MAU (monthly active user)",
        "url": "https://aws.amazon.com/cognito/",
        "icon": "🔐",
        "static_limits": [
            {"name": "User pools per account", "value": "1,000"},
            {"name": "App clients per pool", "value": "1,000"},
            {"name": "Custom attributes per pool", "value": "50"},
            {"name": "Groups per pool", "value": "10,000"},
        ],
    },
    {
        "id": "aurora-serverless",
        "name": "Amazon Aurora Serverless",
        "category": "Database",
        "service_code": "rds",
        "description": "On-demand, auto-scaling relational database compatible with MySQL and PostgreSQL.",
        "useCases": ["Variable workloads", "Dev/test databases", "Infrequent access apps", "Multi-tenant SaaS"],
        "pricing": "Pay per ACU (Aurora Capacity Unit) per second",
        "url": "https://aws.amazon.com/rds/aurora/serverless/",
        "icon": "🌐",
        "static_limits": [
            {"name": "Min ACU", "value": "0.5"},
            {"name": "Max ACU", "value": "256"},
            {"name": "Max storage", "value": "128 TiB"},
            {"name": "Max connections (per ACU)", "value": "~45"},
        ],
    },
    {
        "id": "appsync",
        "name": "AWS AppSync",
        "category": "Integration",
        "service_code": "appsync",
        "description": "Managed GraphQL service to build data-driven apps with real-time and offline capabilities.",
        "useCases": ["GraphQL APIs", "Real-time data sync", "Offline apps", "Data aggregation"],
        "pricing": "Pay per query and real-time update",
        "url": "https://aws.amazon.com/appsync/",
        "icon": "🔺",
        "static_limits": [
            {"name": "Request payload", "value": "1 MB"},
            {"name": "Subscription payload", "value": "240 KB"},
            {"name": "Resolvers per API", "value": "10,000"},
            {"name": "Request timeout", "value": "30 seconds"},
        ],
    },
]
