SERVICES = [
    {
        "id": "lambda",
        "name": "AWS Lambda",
        "category": "Compute",
        "service_code": "lambda",
        "pricing_code": "AWSLambda",
        "description": "AWS Lambda is a serverless, event-driven compute service that lets you run code for virtually any type of application or backend service without provisioning or managing servers.",
        "useCases": ["APIs", "Event processing", "Data transformation", "Scheduled tasks"],
        "pricing": "Pay per request and compute duration",
        "pricingUrl": "https://aws.amazon.com/lambda/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/Lambda",
        "url": "https://aws.amazon.com/lambda/",
        "icon": "⚡",
        "news_keywords": ["Lambda"],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/"],
        "docs_limits_url": "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.md",
        "static_limits": [
            {"name": "Memory", "value": "128 MB – 10,240 MB"},
            {"name": "Timeout", "value": "900 seconds (15 min)"},
            {"name": "Package size (zip)", "value": "50 MB compressed, 250 MB uncompressed"},
            {"name": "Container image size", "value": "10 GB"},
            {"name": "Ephemeral storage (/tmp)", "value": "512 MB – 10,240 MB"},
            {"name": "Payload (sync)", "value": "6 MB"},
            {"name": "Payload (async)", "value": "256 KB"},
            {"name": "Environment variables", "value": "4 KB total"},
        ],
        "runtimes": [
            {"name": "Node.js 22", "status": "active", "eol": "2027-04-30"},
            {"name": "Node.js 20", "status": "active", "eol": "2026-04-30"},
            {"name": "Python 3.13", "status": "active", "eol": "2029-10-01"},
            {"name": "Python 3.12", "status": "active", "eol": "2028-10-01"},
            {"name": "Java 21", "status": "active", "eol": "2028-09-01"},
            {"name": "Java 17", "status": "active", "eol": "2027-09-01"},
            {"name": ".NET 8", "status": "active", "eol": "2026-11-10"},
            {"name": "Ruby 3.3", "status": "active", "eol": "2027-03-31"},
            {"name": "Go (provided.al2023)", "status": "active"},
            {"name": "Rust (provided.al2023)", "status": "active"},
            {"name": "Node.js 18", "status": "deprecated", "eol": "2025-04-30"},
            {"name": "Python 3.9", "status": "deprecated", "eol": "2025-10-01"},
            {"name": "Java 11", "status": "deprecated", "eol": "2025-01-01"},
        ],
    },
    {
        "id": "dynamodb",
        "name": "Amazon DynamoDB",
        "category": "Database",
        "service_code": "dynamodb",
        "pricing_code": "AmazonDynamoDB",
        "description": "Amazon DynamoDB is a serverless, NoSQL, fully managed database with single-digit millisecond performance at any scale.",
        "useCases": ["Key-value store", "Session management", "Real-time analytics", "IoT data"],
        "pricing": "Pay per read/write capacity unit or on-demand",
        "pricingUrl": "https://aws.amazon.com/dynamodb/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/DynamoDB",
        "url": "https://aws.amazon.com/dynamodb/",
        "icon": "🗄️",
        "news_keywords": ["DynamoDB"],
        "integrations_config": [
            {"sdk_client": "dynamodb", "shape_name": "StreamViewType", "label": "Stream View Types", "description": "Data captured in DynamoDB Streams for change data capture"},
        ],
        "blog_feeds": ["https://aws.amazon.com/blogs/database/feed/"],
        "docs_limits_url": "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.md",
        "static_limits": [
            {"name": "Item size", "value": "400 KB"},
            {"name": "Partition key length", "value": "2048 bytes"},
            {"name": "Sort key length", "value": "1024 bytes"},
            {"name": "GSIs per table", "value": "20"},
            {"name": "LSIs per table", "value": "5"},
            {"name": "Projected attributes per index", "value": "100"},
        ],
    },
    {
        "id": "sqs",
        "name": "Amazon SQS",
        "category": "Integration",
        "service_code": "sqs",
        "pricing_code": "AmazonSQS",
        "description": "Amazon SQS is a fully managed message queuing service that enables you to decouple and scale microservices, distributed systems, and serverless applications.",
        "useCases": ["Message queuing", "Decoupling services", "Buffering", "Batch processing"],
        "pricing": "Pay per million requests",
        "pricingUrl": "https://aws.amazon.com/sqs/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/SQS",
        "url": "https://aws.amazon.com/sqs/",
        "icon": "📬",
        "news_keywords": ["SQS", "Simple Queue Service"],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/", "https://aws.amazon.com/blogs/messaging-and-targeting/feed/"],
        "static_limits": [
            {"name": "Message size", "value": "256 KB"},
            {"name": "Message retention", "value": "1 min – 14 days"},
            {"name": "Visibility timeout", "value": "0 s – 12 hours"},
            {"name": "Long poll wait", "value": "0 – 20 seconds"},
            {"name": "Batch size", "value": "10 messages"},
            {"name": "In-flight (standard)", "value": "120,000"},
            {"name": "In-flight (FIFO)", "value": "20,000"},
        ],
    },
    {
        "id": "api-gateway",
        "name": "Amazon API Gateway",
        "category": "Integration",
        "service_code": "apigateway",
        "pricing_code": "AmazonApiGateway",
        "description": "Amazon API Gateway is a fully managed service that makes it easy for developers to create, publish, maintain, monitor, and secure APIs at any scale.",
        "useCases": ["REST APIs", "WebSocket APIs", "HTTP APIs", "API management"],
        "pricing": "Pay per API call and data transfer",
        "pricingUrl": "https://aws.amazon.com/api-gateway/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/APIGateway",
        "url": "https://aws.amazon.com/api-gateway/",
        "icon": "🔗",
        "news_keywords": ["API Gateway"],
        "integrations_config": [
            {"sdk_client": "apigateway", "shape_name": "IntegrationType", "label": "Integration Types", "description": "Backend integration methods for API endpoints"},
            {"sdk_client": "apigateway", "shape_name": "EndpointType", "label": "Endpoint Types", "description": "API endpoint deployment options"},
            {"sdk_client": "apigateway", "shape_name": "AuthorizerType", "label": "Authorizer Types", "description": "Authentication methods for API access control"},
        ],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/"],
        "docs_limits_url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.md",
        "static_limits": [
            {"name": "Payload size", "value": "10 MB"},
            {"name": "Timeout (REST)", "value": "29 seconds"},
            {"name": "Timeout (HTTP API)", "value": "30 seconds"},
            {"name": "Timeout (WebSocket)", "value": "2 hours idle, 10 min message"},
        ],
    },
    {
        "id": "s3",
        "name": "Amazon S3",
        "category": "Storage",
        "service_code": "s3",
        "pricing_code": "AmazonS3",
        "description": "Amazon S3 is an object storage service offering industry-leading scalability, data availability, security, and performance.",
        "useCases": ["Static hosting", "Data lake", "Backup", "Content distribution"],
        "pricing": "Pay per GB stored and requests",
        "pricingUrl": "https://aws.amazon.com/s3/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/S3",
        "url": "https://aws.amazon.com/s3/",
        "icon": "📦",
        "news_keywords": ["Amazon S3", "Simple Storage Service"],
        "integrations_config": [
            {"sdk_client": "s3", "shape_name": "Event", "label": "Event Notifications", "description": "Events that can trigger notifications to SNS, SQS, or Lambda"},
        ],
        "blog_feeds": ["https://aws.amazon.com/blogs/storage/feed/"],
        "docs_limits_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.md",
        "static_limits": [
            {"name": "Object size", "value": "5 TB"},
            {"name": "PUT/COPY/POST/DELETE", "value": "3,500 req/s per prefix"},
            {"name": "GET/HEAD", "value": "5,500 req/s per prefix"},
            {"name": "Metadata size", "value": "2 KB"},
        ],
    },
    {
        "id": "appsync",
        "name": "AWS AppSync",
        "category": "Integration",
        "service_code": "appsync",
        "pricing_code": "AWSAppSync",
        "description": "AWS AppSync is a fully managed service that makes it easy to develop GraphQL APIs by handling the heavy lifting of securely connecting to data sources like DynamoDB, Lambda, and more.",
        "useCases": ["GraphQL APIs", "Real-time data sync", "Offline apps", "Data aggregation"],
        "pricing": "Pay per query and real-time update",
        "pricingUrl": "https://aws.amazon.com/appsync/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/AppSync",
        "url": "https://aws.amazon.com/appsync/",
        "icon": "🔺",
        "news_keywords": ["AppSync"],
        "integrations_config": [
            {"sdk_client": "appsync", "shape_name": "DataSourceType", "label": "Data Sources", "description": "Backends that AppSync can connect to as resolvers for your GraphQL API"},
        ],
        "blog_feeds": ["https://aws.amazon.com/blogs/mobile/feed/"],
        "docs_limits_url": "https://docs.aws.amazon.com/appsync/latest/devguide/quotas.md",
        "static_limits": [
            {"name": "Request payload", "value": "1 MB"},
            {"name": "Subscription payload", "value": "240 KB"},
            {"name": "Resolvers per API", "value": "10,000"},
            {"name": "Request timeout", "value": "30 seconds"},
        ],
    },
    {
        "id": "eventbridge",
        "name": "Amazon EventBridge",
        "category": "Integration",
        "service_code": "events",
        "pricing_code": "AmazonEventBridge",
        "description": "Amazon EventBridge is a serverless event bus that makes it easier to build event-driven applications at scale using events generated from your applications, integrated SaaS applications, and AWS services.",
        "useCases": ["Event-driven architecture", "SaaS integration", "Scheduling", "Cross-account events"],
        "pricing": "Pay per event published",
        "pricingUrl": "https://aws.amazon.com/eventbridge/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/EventBridge",
        "url": "https://aws.amazon.com/eventbridge/",
        "icon": "📡",
        "news_keywords": ["EventBridge"],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/"],
        "static_limits": [
            {"name": "Event size", "value": "256 KB"},
            {"name": "Rules per event bus", "value": "300"},
            {"name": "Targets per rule", "value": "5"},
            {"name": "Invocation rate", "value": "10,000/s (soft)"},
        ],
    },
    {
        "id": "sns",
        "name": "Amazon SNS",
        "category": "Integration",
        "service_code": "sns",
        "pricing_code": "AmazonSNS",
        "description": "Amazon SNS is a fully managed messaging service for both application-to-application and application-to-person communication.",
        "useCases": ["Push notifications", "Fan-out patterns", "Alerts", "Email/SMS delivery"],
        "pricing": "Pay per publish and delivery",
        "pricingUrl": "https://aws.amazon.com/sns/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/SNS",
        "url": "https://aws.amazon.com/sns/",
        "icon": "📢",
        "news_keywords": ["SNS", "Simple Notification Service"],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/", "https://aws.amazon.com/blogs/messaging-and-targeting/feed/"],
        "static_limits": [
            {"name": "Message size", "value": "256 KB"},
            {"name": "Subscriptions per topic", "value": "12,500,000"},
            {"name": "Topics per account", "value": "100,000"},
            {"name": "Filter policies per account", "value": "200"},
        ],
    },
    {
        "id": "cognito",
        "name": "Amazon Cognito",
        "category": "Security",
        "service_code": "cognito-idp",
        "pricing_code": "AmazonCognito",
        "description": "Amazon Cognito lets you easily add user sign-up and authentication to your mobile and web apps. Amazon Cognito also enables you to authenticate users through an external identity provider.",
        "useCases": ["User authentication", "Social login", "MFA", "User management"],
        "pricing": "Pay per MAU (monthly active user)",
        "pricingUrl": "https://aws.amazon.com/cognito/pricing/",
        "calculatorUrl": "https://calculator.aws/createCalculator/Cognito",
        "url": "https://aws.amazon.com/cognito/",
        "icon": "🔐",
        "news_keywords": ["Cognito"],
        "integrations_config": [
            {"sdk_client": "cognito-idp", "shape_name": "IdentityProviderTypeType", "label": "Identity Providers", "description": "External identity providers for federated authentication"},
        ],
        "blog_feeds": ["https://aws.amazon.com/blogs/security/feed/"],
        "static_limits": [
            {"name": "User pools per account", "value": "1,000"},
            {"name": "App clients per pool", "value": "1,000"},
            {"name": "Custom attributes per pool", "value": "50"},
            {"name": "Groups per pool", "value": "10,000"},
        ],
    },
    {
        "id": "step-functions",
        "name": "AWS Step Functions",
        "category": "Integration",
        "service_code": "states",
        "pricing_code": "AmazonStates",
        "description": "AWS Step Functions is a serverless orchestration service that lets you combine AWS Lambda functions and other AWS services to build business-critical applications.",
        "useCases": ["Workflow orchestration", "ETL pipelines", "Order processing", "ML pipelines"],
        "pricing": "Pay per state transition",
        "pricingUrl": "https://aws.amazon.com/step-functions/pricing/",
        "url": "https://aws.amazon.com/step-functions/",
        "icon": "🔄",
        "news_keywords": ["Step Functions"],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/"],
        "static_limits": [
            {"name": "Max execution time (Standard)", "value": "1 year"},
            {"name": "Max execution time (Express)", "value": "5 minutes"},
            {"name": "Max input/output size", "value": "256 KB"},
            {"name": "Max execution history events", "value": "25,000"},
        ],
    },
    {
        "id": "fargate",
        "name": "AWS Fargate",
        "category": "Compute",
        "service_code": "fargate",
        "pricing_code": "AmazonECS",
        "description": "AWS Fargate is a serverless, pay-as-you-go compute engine that lets you focus on building applications without managing servers, compatible with Amazon ECS and Amazon EKS.",
        "useCases": ["Container workloads", "Microservices", "Batch processing", "CI/CD"],
        "pricing": "Pay per vCPU and memory per second",
        "pricingUrl": "https://aws.amazon.com/fargate/pricing/",
        "url": "https://aws.amazon.com/fargate/",
        "icon": "🐳",
        "news_keywords": ["Fargate"],
        "blog_feeds": ["https://aws.amazon.com/blogs/compute/feed/"],
        "static_limits": [
            {"name": "vCPU", "value": "0.25 – 16"},
            {"name": "Memory", "value": "0.5 GB – 120 GB"},
            {"name": "Ephemeral storage", "value": "20 GB – 200 GB"},
        ],
    },
    {
        "id": "ecs",
        "name": "Amazon ECS",
        "category": "Compute",
        "service_code": "ecs",
        "pricing_code": "AmazonECS",
        "description": "Amazon Elastic Container Service is a fully managed container orchestration service that helps you deploy, manage, and scale containerized applications.",
        "useCases": ["Microservices", "Batch processing", "Web apps", "ML inference"],
        "pricing": "No additional charge for ECS; pay for Fargate or EC2 resources",
        "pricingUrl": "https://aws.amazon.com/ecs/pricing/",
        "url": "https://aws.amazon.com/ecs/",
        "icon": "🐳",
        "news_keywords": ["ECS", "Elastic Container Service"],
        "blog_feeds": ["https://aws.amazon.com/blogs/containers/feed/"],
        "static_limits": [
            {"name": "Max containers per task", "value": "10"},
            {"name": "Max tasks per service", "value": "5,000"},
            {"name": "Max services per cluster", "value": "5,000"},
            {"name": "Max clusters per account", "value": "10,000"},
            {"name": "Max vCPU (Fargate)", "value": "16"},
            {"name": "Max memory (Fargate)", "value": "120 GB"},
            {"name": "Max ephemeral storage (Fargate)", "value": "200 GB"},
            {"name": "Container image size", "value": "No limit (pulled at runtime)"},
            {"name": "Max task definition size", "value": "64 KB"},
            {"name": "Max concurrent tasks (Fargate)", "value": "500 (soft limit)"},
        ],
    },
    {
        "id": "aurora-serverless",
        "name": "Amazon Aurora Serverless",
        "category": "Database",
        "service_code": "rds",
        "pricing_code": "AmazonRDS",
        "description": "Amazon Aurora Serverless is an on-demand, auto-scaling configuration for Amazon Aurora that automatically starts up, shuts down, and scales capacity based on your application's needs.",
        "useCases": ["Variable workloads", "Dev/test databases", "Infrequent access apps", "Multi-tenant SaaS"],
        "pricing": "Pay per ACU (Aurora Capacity Unit) per second",
        "pricingUrl": "https://aws.amazon.com/rds/aurora/pricing/",
        "url": "https://aws.amazon.com/rds/aurora/serverless/",
        "icon": "🌐",
        "news_keywords": ["Aurora Serverless", "Aurora"],
        "blog_feeds": ["https://aws.amazon.com/blogs/database/feed/"],
        "static_limits": [
            {"name": "Min ACU", "value": "0.5"},
            {"name": "Max ACU", "value": "256"},
            {"name": "Max storage", "value": "128 TiB"},
            {"name": "Max connections (per ACU)", "value": "~45"},
        ],
    },
    {
        "id": "kinesis",
        "name": "Amazon Kinesis Data Streams",
        "category": "Analytics",
        "service_code": "kinesis",
        "pricing_code": "AmazonKinesis",
        "description": "Amazon Kinesis Data Streams is a serverless streaming data service that makes it easy to capture, process, and store data streams at any scale.",
        "useCases": ["Real-time analytics", "Log ingestion", "IoT data streaming", "Event-driven processing"],
        "pricing": "Pay per shard hour or on-demand per GB",
        "pricingUrl": "https://aws.amazon.com/kinesis/data-streams/pricing/",
        "url": "https://aws.amazon.com/kinesis/data-streams/",
        "icon": "🌊",
        "news_keywords": ["Kinesis"],
        "blog_feeds": ["https://aws.amazon.com/blogs/big-data/feed/"],
        "static_limits": [
            {"name": "Record size", "value": "1 MB"},
            {"name": "Data retention", "value": "24 hours – 365 days"},
            {"name": "Write throughput per shard", "value": "1 MB/s or 1,000 records/s"},
            {"name": "Read throughput per shard", "value": "2 MB/s"},
        ],
    },
    {
        "id": "bedrock",
        "name": "Amazon Bedrock",
        "category": "AI/ML",
        "service_code": "bedrock",
        "pricing_code": "AmazonBedrock",
        "description": "Amazon Bedrock is a fully managed service that offers a choice of high-performing foundation models from leading AI companies via a single API, along with capabilities to build generative AI applications.",
        "useCases": ["Text generation", "Chatbots", "Image generation", "RAG applications"],
        "pricing": "Pay per input/output token or provisioned throughput",
        "pricingUrl": "https://aws.amazon.com/bedrock/pricing/",
        "url": "https://aws.amazon.com/bedrock/",
        "icon": "🧠",
        "news_keywords": ["Bedrock"],
        "blog_feeds": ["https://aws.amazon.com/blogs/machine-learning/feed/"],
        "static_limits": [
            {"name": "Max input tokens", "value": "Model dependent"},
            {"name": "Max output tokens", "value": "Model dependent"},
            {"name": "Knowledge bases per account", "value": "100"},
            {"name": "Agents per account", "value": "100"},
        ],
    },
    {
        "id": "secrets-manager",
        "name": "AWS Secrets Manager",
        "category": "Security",
        "service_code": "secretsmanager",
        "pricing_code": "AWSSecretsManager",
        "description": "AWS Secrets Manager helps you manage, retrieve, and rotate database credentials, API keys, and other secrets throughout their lifecycles.",
        "useCases": ["Database credentials", "API keys", "Secret rotation", "Cross-account access"],
        "pricing": "Pay per secret per month and per API call",
        "pricingUrl": "https://aws.amazon.com/secrets-manager/pricing/",
        "url": "https://aws.amazon.com/secrets-manager/",
        "icon": "🔑",
        "news_keywords": ["Secrets Manager"],
        "blog_feeds": ["https://aws.amazon.com/blogs/security/feed/"],
        "static_limits": [
            {"name": "Secret value size", "value": "64 KB"},
            {"name": "Secrets per account", "value": "500,000"},
            {"name": "Versions per secret", "value": "100"},
            {"name": "Labels per version", "value": "20"},
        ],
    },
    {
        "id": "eks",
        "name": "Amazon EKS",
        "category": "Compute",
        "service_code": "eks",
        "pricing_code": "AmazonEKS",
        "description": "Amazon Elastic Kubernetes Service is a managed Kubernetes service that makes it easy to run Kubernetes on AWS without needing to install and operate your own control plane.",
        "useCases": ["Container orchestration", "Microservices", "Hybrid deployments", "ML workloads"],
        "pricing": "$0.10 per hour per cluster + compute costs",
        "pricingUrl": "https://aws.amazon.com/eks/pricing/",
        "url": "https://aws.amazon.com/eks/",
        "icon": "☸️",
        "news_keywords": ["EKS", "Elastic Kubernetes"],
        "blog_feeds": ["https://aws.amazon.com/blogs/containers/feed/"],
        "static_limits": [
            {"name": "Nodes per cluster", "value": "5,000"},
            {"name": "Pods per node (max)", "value": "110"},
            {"name": "Services per cluster", "value": "5,000"},
            {"name": "ConfigMaps per namespace", "value": "Unlimited"},
            {"name": "Clusters per region", "value": "100"},
            {"name": "Managed node groups per cluster", "value": "30"},
            {"name": "Fargate profiles per cluster", "value": "10"},
        ],
    },
    {
        "id": "app-runner",
        "name": "AWS App Runner",
        "category": "Compute",
        "service_code": "apprunner",
        "pricing_code": "AWSAppRunner",
        "description": "AWS App Runner is a fully managed service that makes it easy to quickly deploy containerized web applications and APIs at scale with no infrastructure experience required.",
        "useCases": ["Web apps", "APIs", "Microservices", "Rapid prototyping"],
        "pricing": "Pay per vCPU and memory per second when active",
        "pricingUrl": "https://aws.amazon.com/apprunner/pricing/",
        "url": "https://aws.amazon.com/apprunner/",
        "icon": "🏃",
        "news_keywords": ["App Runner"],
        "blog_feeds": ["https://aws.amazon.com/blogs/containers/feed/"],
        "static_limits": [
            {"name": "Max vCPU per instance", "value": "4"},
            {"name": "Max memory per instance", "value": "12 GB"},
            {"name": "Max concurrency per instance", "value": "200"},
            {"name": "Max instances per service", "value": "25"},
            {"name": "Request timeout", "value": "120 seconds"},
            {"name": "Max services per account per region", "value": "25"},
        ],
    },
    {
        "id": "opensearch-serverless",
        "name": "Amazon OpenSearch Serverless",
        "category": "Analytics",
        "service_code": "opensearchserverless",
        "pricing_code": "AmazonOpenSearchService",
        "description": "Amazon OpenSearch Serverless is a serverless option for Amazon OpenSearch Service that makes it simple to run search and analytics workloads without managing clusters.",
        "useCases": ["Log analytics", "Full-text search", "Application monitoring", "Security analytics"],
        "pricing": "Pay per OCU (OpenSearch Compute Unit) per hour",
        "pricingUrl": "https://aws.amazon.com/opensearch-service/pricing/",
        "url": "https://aws.amazon.com/opensearch-service/features/serverless/",
        "icon": "🔍",
        "news_keywords": ["OpenSearch Serverless"],
        "blog_feeds": ["https://aws.amazon.com/blogs/big-data/feed/"],
        "static_limits": [
            {"name": "Max OCUs per account", "value": "50"},
            {"name": "Max collections per account", "value": "50"},
            {"name": "Max indexes per collection", "value": "20"},
            {"name": "Max document size", "value": "16 MB"},
        ],
    },
    {
        "id": "msk-serverless",
        "name": "Amazon MSK Serverless",
        "category": "Streaming",
        "service_code": "kafka",
        "pricing_code": "AmazonMSK",
        "description": "Amazon MSK Serverless is a cluster type for Amazon MSK that makes it easy to run Apache Kafka without managing and scaling cluster capacity.",
        "useCases": ["Event streaming", "Log aggregation", "Data pipelines", "Real-time analytics"],
        "pricing": "Pay per cluster hour, partition hour, and data in/out",
        "pricingUrl": "https://aws.amazon.com/msk/pricing/",
        "url": "https://aws.amazon.com/msk/features/msk-serverless/",
        "icon": "📡",
        "news_keywords": ["MSK Serverless", "MSK"],
        "blog_feeds": ["https://aws.amazon.com/blogs/big-data/feed/"],
        "static_limits": [
            {"name": "Max partitions per cluster", "value": "120"},
            {"name": "Max message size", "value": "8 MB"},
            {"name": "Max retention", "value": "24 hours"},
            {"name": "Max consumer groups", "value": "500"},
            {"name": "Max throughput per partition", "value": "5 MB/s in, 10 MB/s out"},
        ],
    },
    {
        "id": "neptune-serverless",
        "name": "Amazon Neptune Serverless",
        "category": "Database",
        "service_code": "neptune",
        "pricing_code": "AmazonNeptune",
        "description": "Amazon Neptune Serverless lets you run graph database workloads without managing instance capacity, automatically scaling compute based on workload demands.",
        "useCases": ["Knowledge graphs", "Fraud detection", "Social networks", "Recommendation engines"],
        "pricing": "Pay per NCU (Neptune Capacity Unit) per hour",
        "pricingUrl": "https://aws.amazon.com/neptune/pricing/",
        "url": "https://aws.amazon.com/neptune/serverless/",
        "icon": "🔵",
        "news_keywords": ["Neptune Serverless", "Neptune"],
        "blog_feeds": ["https://aws.amazon.com/blogs/database/feed/"],
        "static_limits": [
            {"name": "Min NCU", "value": "1"},
            {"name": "Max NCU", "value": "128"},
            {"name": "Max storage", "value": "128 TiB"},
            {"name": "Max vertices/edges per request", "value": "Unlimited"},
        ],
    },
    {
        "id": "redshift-serverless",
        "name": "Amazon Redshift Serverless",
        "category": "Analytics",
        "service_code": "redshift-serverless",
        "pricing_code": "AmazonRedshift",
        "description": "Amazon Redshift Serverless lets you run and scale analytics without provisioning and managing data warehouse clusters.",
        "useCases": ["Data warehousing", "Business intelligence", "Ad-hoc queries", "Dashboards"],
        "pricing": "Pay per RPU (Redshift Processing Unit) per hour",
        "pricingUrl": "https://aws.amazon.com/redshift/pricing/",
        "url": "https://aws.amazon.com/redshift/redshift-serverless/",
        "icon": "📊",
        "news_keywords": ["Redshift Serverless", "Redshift"],
        "blog_feeds": ["https://aws.amazon.com/blogs/big-data/feed/"],
        "static_limits": [
            {"name": "Base RPU", "value": "8 – 512"},
            {"name": "Max query time", "value": "86,400 seconds (24 hr)"},
            {"name": "Max databases per workgroup", "value": "Unlimited"},
            {"name": "Max concurrent queries", "value": "Varies by RPU"},
        ],
    },
]

DISABLED_SERVICES = []
