SERVICES = [
    {
        "id": "kubernetes-engine",
        "name": "STACKIT Kubernetes Engine",
        "category": "Containers",
        "description": "STACKIT Kubernetes Engine (SKE) is a managed Kubernetes service that lets you deploy, manage, and scale containerized applications on STACKIT infrastructure.",
        "useCases": ["Container orchestration", "Microservices", "CI/CD", "Cloud-native apps"],
        "pricing": "Pay per node hour",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=ske",
        "url": "https://docs.stackit.cloud/stackit/en/stackit-kubernetes-engine-ske-19759461.html",
        "icon": "☸️",
        "news_keywords": ["SKE", "Kubernetes Engine", "Kubernetes"],
        "static_limits": [
            {"name": "Max nodes per cluster", "value": "100"},
            {"name": "Max clusters per project", "value": "10"},
            {"name": "Supported Kubernetes versions", "value": "1.28 – 1.34"},
        ],
    },
    {
        "id": "object-storage",
        "name": "STACKIT Object Storage",
        "category": "Storage",
        "description": "STACKIT Object Storage is an S3-compatible object storage service for storing and retrieving any amount of data at any time.",
        "useCases": ["Data lakes", "Backups", "Static hosting", "Media storage"],
        "pricing": "Pay per GB stored and requests",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=object-storage",
        "url": "https://docs.stackit.cloud/stackit/en/object-storage-15138705.html",
        "icon": "📦",
        "news_keywords": ["Object Storage"],
        "static_limits": [
            {"name": "Max object size", "value": "5 TB"},
            {"name": "S3 compatibility", "value": "Yes"},
            {"name": "Object Lock", "value": "Yes"},
        ],
    },
    {
        "id": "postgresql-flex",
        "name": "STACKIT PostgreSQL Flex",
        "category": "Database",
        "description": "STACKIT PostgreSQL Flex is a fully managed PostgreSQL database service with flexible configuration and high availability.",
        "useCases": ["Relational data", "Web apps", "Analytics", "Transactional workloads"],
        "pricing": "Pay per instance hour and storage",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=postgresql",
        "url": "https://docs.stackit.cloud/stackit/en/postgresql-flex-19759491.html",
        "icon": "🐘",
        "news_keywords": ["PostgreSQL Flex", "PostgreSQL"],
        "static_limits": [
            {"name": "Supported versions", "value": "13, 14, 15, 16, 17"},
            {"name": "Max storage", "value": "2 TB"},
            {"name": "High availability", "value": "Yes"},
        ],
    },
    {
        "id": "mongodb-flex",
        "name": "STACKIT MongoDB Flex",
        "category": "Database",
        "description": "STACKIT MongoDB Flex is a fully managed MongoDB-compatible NoSQL database service for document-oriented workloads.",
        "useCases": ["Document storage", "Real-time apps", "Catalogs", "Content management"],
        "pricing": "Pay per instance hour and storage",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=mongodb",
        "url": "https://docs.stackit.cloud/stackit/en/mongodb-flex-19759489.html",
        "icon": "🍃",
        "news_keywords": ["MongoDB Flex", "MongoDB"],
        "static_limits": [
            {"name": "Supported versions", "value": "6, 7"},
            {"name": "Max storage", "value": "2 TB"},
            {"name": "Replica sets", "value": "Yes"},
        ],
    },
    {
        "id": "mariadb",
        "name": "STACKIT MariaDB",
        "category": "Database",
        "description": "STACKIT MariaDB is a fully managed MariaDB relational database service with SSL support and flexible sizing.",
        "useCases": ["Web apps", "E-commerce", "CMS", "Transactional workloads"],
        "pricing": "Pay per instance hour and storage",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=mariadb",
        "url": "https://docs.stackit.cloud/stackit/en/mariadb-19759487.html",
        "icon": "🐬",
        "news_keywords": ["MariaDB"],
        "static_limits": [
            {"name": "Supported versions", "value": "10.6, 10.11"},
            {"name": "SSL support", "value": "Yes"},
            {"name": "Max storage", "value": "2 TB"},
        ],
    },
    {
        "id": "redis",
        "name": "STACKIT Redis",
        "category": "Database",
        "description": "STACKIT Redis is a fully managed in-memory data store for caching, session management, and real-time analytics.",
        "useCases": ["Caching", "Session management", "Leaderboards", "Pub/Sub"],
        "pricing": "Pay per instance hour",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=redis",
        "url": "https://docs.stackit.cloud/stackit/en/redis-19759493.html",
        "icon": "⚡",
        "news_keywords": ["Redis"],
        "static_limits": [
            {"name": "Supported versions", "value": "7"},
            {"name": "Max memory", "value": "Flavor dependent"},
            {"name": "Persistence", "value": "Yes"},
        ],
    },
    {
        "id": "key-value-store",
        "name": "STACKIT Key Value Store",
        "category": "Database",
        "description": "STACKIT Key Value Store is a managed in-memory key-value store based on Valkey, the open-source Redis alternative.",
        "useCases": ["Caching", "Session stores", "Rate limiting", "Real-time data"],
        "pricing": "Pay per instance hour",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=key-value-store",
        "url": "https://docs.stackit.cloud/stackit/en/key-value-store.html",
        "icon": "🗝️",
        "news_keywords": ["Key Value Store", "Valkey"],
        "static_limits": [
            {"name": "Based on", "value": "Valkey (Redis-compatible)"},
            {"name": "Persistence", "value": "Yes"},
        ],
    },
    {
        "id": "opensearch",
        "name": "STACKIT OpenSearch",
        "category": "Database",
        "description": "STACKIT OpenSearch is a fully managed OpenSearch service for search, log analytics, and observability workloads.",
        "useCases": ["Full-text search", "Log analytics", "Observability", "Security analytics"],
        "pricing": "Pay per instance hour and storage",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=opensearch",
        "url": "https://docs.stackit.cloud/stackit/en/opensearch-19759490.html",
        "icon": "🔍",
        "news_keywords": ["OpenSearch"],
        "static_limits": [
            {"name": "Supported versions", "value": "2.x"},
            {"name": "Max storage", "value": "Flavor dependent"},
            {"name": "High availability", "value": "Yes"},
        ],
    },
    {
        "id": "rabbitmq",
        "name": "STACKIT RabbitMQ",
        "category": "Integration",
        "description": "STACKIT RabbitMQ is a fully managed message broker service for decoupling applications and enabling async communication.",
        "useCases": ["Message queuing", "Event streaming", "Decoupling services", "Task queues"],
        "pricing": "Pay per instance hour",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=rabbitmq",
        "url": "https://docs.stackit.cloud/stackit/en/rabbitmq-19759492.html",
        "icon": "🐇",
        "news_keywords": ["RabbitMQ"],
        "static_limits": [
            {"name": "Supported versions", "value": "3.13, 4.0"},
            {"name": "Protocols", "value": "AMQP, MQTT, STOMP"},
            {"name": "High availability", "value": "Yes"},
        ],
    },
    {
        "id": "secrets-manager",
        "name": "STACKIT Secrets Manager",
        "category": "Security",
        "description": "STACKIT Secrets Manager is a secure service for storing and managing secrets, API keys, certificates, and sensitive configuration.",
        "useCases": ["Secret storage", "API keys", "Certificates", "Configuration management"],
        "pricing": "Pay per secret per month",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=secrets-manager",
        "url": "https://docs.stackit.cloud/stackit/en/secrets-manager-19759494.html",
        "icon": "🔐",
        "news_keywords": ["Secrets Manager"],
        "static_limits": [
            {"name": "Audit log", "value": "Yes"},
            {"name": "JSON editor", "value": "Yes"},
        ],
    },
    {
        "id": "kms",
        "name": "STACKIT Key Management Service",
        "category": "Security",
        "description": "STACKIT KMS is a managed key management service for creating, storing, and controlling cryptographic keys.",
        "useCases": ["Key management", "Encryption", "Data protection", "Compliance"],
        "pricing": "Pay per key per month and API calls",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=kms",
        "url": "https://docs.stackit.cloud/stackit/en/key-management-service-kms.html",
        "icon": "🔑",
        "news_keywords": ["KMS", "Key Management Service"],
        "static_limits": [
            {"name": "Regions", "value": "EU01, EU02"},
            {"name": "Post-quantum support", "value": "Yes (AES-KW)"},
        ],
    },
    {
        "id": "load-balancer",
        "name": "STACKIT Application Load Balancer",
        "category": "Networking",
        "description": "STACKIT Application Load Balancer distributes incoming traffic across multiple targets with support for WAF and advanced routing.",
        "useCases": ["Traffic distribution", "High availability", "SSL termination", "WAF"],
        "pricing": "Pay per hour and data processed",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=alb",
        "url": "https://docs.stackit.cloud/stackit/en/application-load-balancer.html",
        "icon": "⚖️",
        "news_keywords": ["Application Load Balancer", "ALB", "Load Balancer"],
        "static_limits": [
            {"name": "WAF support", "value": "Yes (GA)"},
            {"name": "Protocols", "value": "HTTP, HTTPS, TCP"},
        ],
    },
    {
        "id": "dns",
        "name": "STACKIT DNS",
        "category": "Networking",
        "description": "STACKIT DNS is a managed DNS service with support for external DNS providers, ACME issuers, and bulk domain management.",
        "useCases": ["Domain management", "DNS routing", "Cert-Manager integration", "ExternalDNS"],
        "pricing": "Pay per zone and queries",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=dns",
        "url": "https://docs.stackit.cloud/stackit/en/dns-19759462.html",
        "icon": "🌐",
        "news_keywords": ["DNS"],
        "static_limits": [
            {"name": "ExternalDNS support", "value": "Yes"},
            {"name": "ACME DNS01 support", "value": "Yes"},
            {"name": "Bulk domain ordering", "value": "Yes"},
        ],
    },
    {
        "id": "cdn",
        "name": "STACKIT CDN",
        "category": "Networking",
        "description": "STACKIT Content Delivery Network accelerates content delivery with global edge caching, WAF, and image optimization.",
        "useCases": ["Static content delivery", "Web acceleration", "Media streaming", "WAF"],
        "pricing": "Pay per GB transferred",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=cdn",
        "url": "https://docs.stackit.cloud/stackit/en/cdn.html",
        "icon": "🚀",
        "news_keywords": ["CDN", "Content Delivery Network"],
        "static_limits": [
            {"name": "WAF support", "value": "Yes"},
            {"name": "Image optimizer", "value": "Yes"},
        ],
    },
    {
        "id": "vpn",
        "name": "STACKIT VPN",
        "category": "Networking",
        "description": "STACKIT VPN provides secure site-to-site and client VPN connectivity for your cloud resources.",
        "useCases": ["Secure connectivity", "Hybrid cloud", "Remote access", "Network isolation"],
        "pricing": "Pay per hour",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=vpn",
        "url": "https://docs.stackit.cloud/stackit/en/vpn.html",
        "icon": "🔒",
        "news_keywords": ["VPN"],
        "static_limits": [
            {"name": "API available", "value": "Yes"},
            {"name": "Protocols", "value": "IPsec"},
        ],
    },
    {
        "id": "logs",
        "name": "STACKIT Logs",
        "category": "Observability",
        "description": "STACKIT Logs is a managed log management service based on Grafana Loki for ingesting, storing, and querying logs.",
        "useCases": ["Log aggregation", "Troubleshooting", "Compliance", "Security monitoring"],
        "pricing": "Pay per GB ingested",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=logs",
        "url": "https://docs.stackit.cloud/stackit/en/logs.html",
        "icon": "📋",
        "news_keywords": ["Logs", "Loki"],
        "static_limits": [
            {"name": "Based on", "value": "Grafana Loki"},
            {"name": "OTLP ingestion", "value": "Yes"},
            {"name": "Pattern extraction", "value": "Yes"},
        ],
    },
    {
        "id": "observability",
        "name": "STACKIT Observability",
        "category": "Observability",
        "description": "STACKIT Observability provides a managed monitoring stack with Grafana, Prometheus-compatible metrics, and Alertmanager.",
        "useCases": ["Metrics monitoring", "Alerting", "Dashboards", "Infrastructure monitoring"],
        "pricing": "Pay per metric series and retention",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=observability",
        "url": "https://docs.stackit.cloud/stackit/en/observability.html",
        "icon": "📊",
        "news_keywords": ["Observability", "Grafana", "Alertmanager"],
        "static_limits": [
            {"name": "Based on", "value": "Grafana + Prometheus"},
            {"name": "Alertmanager", "value": "Yes"},
            {"name": "Google Chat webhooks", "value": "Yes"},
        ],
    },
    {
        "id": "ai-model-serving",
        "name": "STACKIT AI Model Serving",
        "category": "AI/ML",
        "description": "STACKIT AI Model Serving provides a managed inference API for running large language models and multimodal AI models on sovereign European infrastructure.",
        "useCases": ["LLM inference", "Text generation", "Embeddings", "Multimodal AI"],
        "pricing": "Pay per token",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=ai-model-serving",
        "url": "https://docs.stackit.cloud/stackit/en/ai-model-serving.html",
        "icon": "🧠",
        "news_keywords": ["AI Model Serving", "AI Model"],
        "runtimes": [
            {"name": "GPT-OSS 120B", "status": "active"},
            {"name": "GPT-OSS 20B", "status": "active"},
            {"name": "Qwen3-VL-235B", "status": "active"},
            {"name": "Qwen3-VL-Embedding-8B", "status": "active"},
            {"name": "Google Gemma 4", "status": "active"},
            {"name": "Llama-8B", "status": "deprecated"},
            {"name": "Nemo", "status": "deprecated"},
            {"name": "Google Gemma 3", "status": "deprecated"},
        ],
        "static_limits": [
            {"name": "Infrastructure", "value": "Sovereign EU (STACKIT)"},
            {"name": "API compatibility", "value": "OpenAI-compatible"},
        ],
    },
    {
        "id": "container-registry",
        "name": "STACKIT Container Registry",
        "category": "Containers",
        "description": "STACKIT Container Registry is a managed private container image registry for storing and distributing Docker images.",
        "useCases": ["Image storage", "CI/CD pipelines", "Private registries", "Image distribution"],
        "pricing": "Pay per GB stored",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=container-registry",
        "url": "https://docs.stackit.cloud/stackit/en/container-registry.html",
        "icon": "🐳",
        "news_keywords": ["Container Registry"],
        "static_limits": [
            {"name": "Private registries", "value": "Yes"},
            {"name": "Docker compatible", "value": "Yes"},
        ],
    },
    {
        "id": "server",
        "name": "STACKIT Server",
        "category": "Compute",
        "description": "STACKIT Server provides virtual machines on sovereign European cloud infrastructure with flexible sizing and multiple hardware generations.",
        "useCases": ["General compute", "Web hosting", "Databases", "Development environments"],
        "pricing": "Pay per hour (vCPU + RAM)",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=server",
        "url": "https://docs.stackit.cloud/stackit/en/virtual-servers-19759459.html",
        "icon": "🖥️",
        "news_keywords": ["Server", "Virtual Machine"],
        "static_limits": [
            {"name": "Min vCPU", "value": "1"},
            {"name": "Max vCPU", "value": "Flavor dependent"},
            {"name": "Hardware", "value": "Intel (2nd/3rd gen)"},
            {"name": "OS options", "value": "Ubuntu, openSUSE, RHEL, Windows"},
        ],
    },
    {
        "id": "cloud-foundry",
        "name": "STACKIT Cloud Foundry",
        "category": "Compute",
        "description": "STACKIT Cloud Foundry is a managed Platform-as-a-Service for deploying and scaling applications without managing infrastructure.",
        "useCases": ["App deployment", "PaaS", "Microservices", "Rapid development"],
        "pricing": "Pay per instance hour",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=cloud-foundry",
        "url": "https://docs.stackit.cloud/stackit/en/cloud-foundry-19759460.html",
        "icon": "☁️",
        "news_keywords": ["Cloud Foundry"],
        "static_limits": [
            {"name": "Max RAM per instance", "value": "32 GB"},
            {"name": "Buildpacks", "value": "Yes"},
        ],
    },
    {
        "id": "git",
        "name": "STACKIT Git",
        "category": "DevOps",
        "description": "STACKIT Git is a managed Git hosting service for sovereign source code management on European infrastructure.",
        "useCases": ["Source control", "Code collaboration", "CI/CD", "DevOps"],
        "pricing": "Pay per subscription plan",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=git",
        "url": "https://docs.stackit.cloud/stackit/en/git.html",
        "icon": "📁",
        "news_keywords": ["STACKIT Git"],
        "static_limits": [
            {"name": "Based on", "value": "Gitea"},
            {"name": "Sovereign hosting", "value": "Yes (EU)"},
        ],
    },
    {
        "id": "pipelines",
        "name": "STACKIT Pipelines",
        "category": "DevOps",
        "description": "STACKIT Pipelines is a managed CI/CD service with STACKIT-managed runners for building and deploying applications.",
        "useCases": ["CI/CD", "Automated testing", "Build automation", "Deployment pipelines"],
        "pricing": "Pay per build minute",
        "pricingUrl": "https://www.stackit.com/en/prices",
        "calculatorUrl": "https://calculator.stackit.cloud/runtime?addService=pipelines",
        "url": "https://docs.stackit.cloud/stackit/en/pipelines.html",
        "icon": "🔧",
        "news_keywords": ["Pipelines"],
        "static_limits": [
            {"name": "Managed runners", "value": "Yes"},
            {"name": "Pipeline approvals", "value": "Yes"},
        ],
    },
]

DISABLED_SERVICES = []
